/**
 * OnPause hook component (Phase C migration).
 * Source: hooks/on-pause.md
 */

import type { Component } from "../types";

const OnPause: Component = {
  name: "OnPause",
  category: "hooks",
  description: "Actions to perform when work is paused, generates continuation file",
  sections: {
    Default: {
      name: "Default",
      description: "OnPause default body",
      body: `# On-Pause Hook

Actions performed when the user requests to pause work or when a session ends naturally.

---

## Trigger

Fires when:
- User explicitly requests to pause (\`/st:pause\`)
- Session is ending (user leaves)
- Blocking issue encountered (Rule 4 deviation)
- Checkpoint requires extended user action

---

## Purpose

Create a continuation file that enables seamless resumption:
1. Capture current position precisely
2. Record context that would be lost
3. Provide clear next action
4. Enable fresh context resumption

---

## Actions

### 1. Capture Current State

\`\`\`bash
# Read current state
cat .software-teams/config/state.yaml

# Extract position
PHASE=$(yq -r '.position.phase' .software-teams/config/state.yaml)
PLAN=$(yq -r '.position.plan' .software-teams/config/state.yaml)
TASK=$(yq -r '.position.task' .software-teams/config/state.yaml)
STATUS=$(yq -r '.position.status' .software-teams/config/state.yaml)
\`\`\`

### 2. Identify Next Action

Based on current status, determine what should happen next:

| Status | Next Action |
|--------|-------------|
| \`planning\` | Continue planning |
| \`executing\` | Resume task execution |
| \`verifying\` | Complete verification |
| \`blocked\` | Resolve blocker |
| \`checkpoint\` | Await user response |

### 3. Capture Session Context

Gather context that would be lost:
- Recent decisions made
- Key discoveries
- Warnings or concerns
- User preferences expressed

### 4. Generate Continuation File

Create \`.software-teams/CONTINUE-HERE.md\`:

\`\`\`markdown
---
paused_at: {ISO timestamp}
phase: {N}
plan: {NN}
task: {N or null}
status: {status}
---

# Continue Here

## Quick Resume

**Last completed:** {description of last completed work}
**Current status:** {what's in progress}
**Next action:** \`{command to run}\`

## Position

| Level | Value | Name |
|-------|-------|------|
| Phase | {N} | {phase_name} |
| Plan | {NN} | {plan_name} |
| Task | {N} | {task_name or "N/A"} |
| Status | {status} | |

## Context from This Session

### Decisions Made
{List of decisions made during this session}

### Key Discoveries
{Important findings or learnings}

### Warnings/Concerns
{Any issues to be aware of}

### User Preferences
{Any preferences expressed by user}

## To Resume

### Option 1: Continue Where Left Off
\`\`\`bash
/st:resume
\`\`\`

### Option 2: Manual Resume
\`\`\`bash
# If task was in progress:
/st:implement-plan {phase}-{plan} --resume-from-task {task}

# If planning:
/st:create-plan {phase}

# If verifying:
/st:verify {phase}
\`\`\`

## Recent Commits

| Time | Hash | Message |
|------|------|---------|
{List recent commits from session}

## Files Modified (Uncommitted)

\`\`\`bash
git status --short
\`\`\`

{Output of uncommitted changes, if any}

## Blockers (if any)

{Description of any blocking issues}

---

*Generated by Software Teams on-pause hook at {timestamp}*
\`\`\`

### 5. Update State

Mark session as paused:

\`\`\`yaml
position:
  status: paused
session:
  paused_at: "{timestamp}"
  continuation_file: ".software-teams/CONTINUE-HERE.md"
\`\`\`

### 6. Display Pause Summary

\`\`\`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Software Teams ► SESSION PAUSED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Paused at: Phase {N}, Plan {NN}, Task {N}
Status: {status}

Continuation file: .software-teams/CONTINUE-HERE.md

To resume: /st:resume

───────────────────────────────────────────────────────
\`\`\`

---

## Continuation File Location

The continuation file is always at: \`.software-teams/CONTINUE-HERE.md\`

This file is:
- Overwritten on each pause (only one active)
- Deleted after successful resume
- Human-readable for manual recovery

---

## Integration with Resume

The \`/st:resume\` command:
1. Reads \`.software-teams/CONTINUE-HERE.md\`
2. Loads context specified in the file
3. Executes the \`next_action\`
4. Deletes the continuation file on success

---

## Success Criteria

- [ ] Current position captured accurately
- [ ] Next action clearly identified
- [ ] Session context preserved
- [ ] Continuation file is self-contained
- [ ] State updated to paused
- [ ] User informed of how to resume`,
    },
  },
  defaultOrder: ["Default"],
};

export default OnPause;
