import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildAgentDefinition, parseSpecFrontmatter } from "../agent-definition";

const dirs: string[] = [];

function fixture(agentId: string, spec: string): string {
  const root = mkdtempSync(join(tmpdir(), "st-agentdef-"));
  dirs.push(root);
  mkdirSync(join(root, ".claude", "agents"), { recursive: true });
  writeFileSync(join(root, ".claude", "agents", `${agentId}.md`), spec, "utf8");
  return root;
}

afterAll(() => {
  for (const d of dirs) rmSync(d, { recursive: true, force: true });
});

const SPEC = [
  "---",
  "name: software-teams-backend",
  "description: Backend engineer",
  "model: opus",
  "effort: high",
  "tools:",
  "  - Read",
  "  - Edit",
  "  - Bash",
  "---",
  "",
  "<!-- AUTO-GENERATED by software-teams sync-agents — edit and re-run -->",
  "",
  "You are the Backend Engineer.",
].join("\n");

describe("parseSpecFrontmatter", () => {
  test("reads scalars, sequences, and the body", () => {
    const { meta, body } = parseSpecFrontmatter(SPEC);
    expect(meta["model"]).toBe("opus");
    expect(meta["effort"]).toBe("high");
    expect(meta["tools"]).toEqual(["Read", "Edit", "Bash"]);
    expect(body).toContain("You are the Backend Engineer.");
  });

  test("a file with no frontmatter yields no metadata rather than throwing", () => {
    const { meta, body } = parseSpecFrontmatter("just a body");
    expect(meta).toEqual({});
    expect(body).toBe("just a body");
  });
});

describe("buildAgentDefinition", () => {
  test("carries the spec's identity, tools, model, and effort", () => {
    const root = fixture("software-teams-backend", SPEC);
    const def = buildAgentDefinition({
      agentId: "software-teams-backend",
      baseDir: root,
      structuredOutput: false,
    });

    expect(def).not.toBeNull();
    expect(def?.description).toBe("Backend engineer");
    expect(def?.model).toBe("opus");
    expect(def?.effort).toBe("high");
    expect(def?.tools).toEqual(["Read", "Edit", "Bash"]);
    // The body becomes the agent's SYSTEM prompt rather than user-turn text.
    expect(def?.prompt).toContain("You are the Backend Engineer.");
    // Generator banners are not instructions.
    expect(def?.prompt).not.toContain("AUTO-GENERATED");
  });

  test("grants StructuredOutput when structured output is requested", () => {
    // Without this, a restricted tools list silently disables --json-schema:
    // the tool is filtered out, the model cannot emit the object, and
    // structured_output comes back null with no error at all.
    const root = fixture("software-teams-backend", SPEC);
    const def = buildAgentDefinition({
      agentId: "software-teams-backend",
      baseDir: root,
      structuredOutput: true,
    });
    expect(def?.tools).toContain("StructuredOutput");
    expect(def?.tools).toContain("Read");
  });

  test("does not duplicate StructuredOutput when the spec already grants it", () => {
    const root = fixture(
      "dup",
      ["---", "description: d", "tools:", "  - Read", "  - StructuredOutput", "---", "body"].join(
        "\n",
      ),
    );
    const def = buildAgentDefinition({ agentId: "dup", baseDir: root, structuredOutput: true });
    expect(def?.tools?.filter((t) => t === "StructuredOutput")).toHaveLength(1);
  });

  test("always withholds the spawning tool — one node is one turn", () => {
    const root = fixture("software-teams-backend", SPEC);
    const def = buildAgentDefinition({
      agentId: "software-teams-backend",
      baseDir: root,
      structuredOutput: true,
    });
    expect(def?.disallowedTools).toContain("Agent");
  });

  test("overrides beat the spec", () => {
    const root = fixture("software-teams-backend", SPEC);
    const def = buildAgentDefinition({
      agentId: "software-teams-backend",
      baseDir: root,
      structuredOutput: true,
      overrides: { model: "haiku", effort: "low", tools: ["Read", "Grep"] },
    });
    expect(def?.model).toBe("haiku");
    expect(def?.effort).toBe("low");
    expect(def?.tools).toEqual(["Read", "Grep", "StructuredOutput"]);
    expect(def?.tools).not.toContain("Edit");
  });

  test("a spec with no tools list leaves tools unrestricted", () => {
    const root = fixture("bare", ["---", "description: d", "---", "body"].join("\n"));
    const def = buildAgentDefinition({ agentId: "bare", baseDir: root, structuredOutput: true });
    expect(def?.tools).toBeUndefined();
  });

  test("returns null when no spec exists, rather than failing the turn", () => {
    const root = fixture("present", ["---", "description: d", "---", "body"].join("\n"));
    expect(
      buildAgentDefinition({ agentId: "absent", baseDir: root, structuredOutput: true }),
    ).toBeNull();
  });

  test("serialises to the shape the --agents flag accepts", () => {
    const root = fixture("software-teams-backend", SPEC);
    const def = buildAgentDefinition({
      agentId: "software-teams-backend",
      baseDir: root,
      structuredOutput: true,
    });
    const json = JSON.parse(JSON.stringify({ "software-teams-backend": def })) as Record<
      string,
      Record<string, unknown>
    >;
    const entry = json["software-teams-backend"];
    expect(typeof entry?.["description"]).toBe("string");
    expect(typeof entry?.["prompt"]).toBe("string");
    expect(Array.isArray(entry?.["tools"])).toBe(true);
  });
});
