import { describe, test, expect, mock, beforeEach } from "bun:test";
import { resolve, join } from "node:path";
import { readFileSync } from "node:fs";
import type { NodeEnvelope } from "@websitelabs/software-teams";

const pkgRoot = resolve(import.meta.dir, "..", "..", "..");
const builtAgentsDir = resolve(pkgRoot, "dist", "agents");
const installedSingleTurnDir = resolve(pkgRoot, "dist", "src", "execution");

function installedResolve(agentId: string): string {
  return join(installedSingleTurnDir, "..", "..", "agents", `${agentId}.md`);
}

function stripSpecFrontmatter(content: string): string {
  const fm = content.match(/^---\n[\s\S]*?\n---\n?/);
  const rawBody = fm ? content.slice(fm[0].length) : content;
  return rawBody
    .replace(/^\s*<!--\s*AUTO-GENERATED[\s\S]*?-->\s*\n?/, "")
    .replace(/^\s*<!--\s*canonical frontmatter[\s\S]*?-->\s*\n?/, "")
    .trim();
}

function personaBody(agentId: string): string {
  return stripSpecFrontmatter(readFileSync(installedResolve(agentId), "utf8"));
}

describe("persona bodies — distinct, non-empty, frontmatter-stripped (AC9)", () => {
  test("a known specialist yields a non-empty persona body in the installed layout", () => {
    const body = personaBody("software-teams-backend");
    expect(body.length).toBeGreaterThan(0);
  });

  test("two different agentIds yield two DIFFERENT non-empty persona bodies (AC9)", () => {
    const backend = personaBody("software-teams-backend");
    const frontend = personaBody("software-teams-frontend");
    expect(backend.length).toBeGreaterThan(0);
    expect(frontend.length).toBeGreaterThan(0);
    expect(backend).not.toBe(frontend);
  });

  test("a third specialist also yields a distinct persona (real specialism, not bare)", () => {
    const security = personaBody("software-teams-security");
    const quality = personaBody("software-teams-quality");
    expect(security.length).toBeGreaterThan(0);
    expect(quality.length).toBeGreaterThan(0);
    expect(security).not.toBe(quality);
    expect(security).not.toBe(personaBody("software-teams-backend"));
  });

  test("stripped body drops YAML frontmatter and the AUTO-GENERATED banner", () => {
    const raw = readFileSync(join(builtAgentsDir, "software-teams-backend.md"), "utf8");
    const body = stripSpecFrontmatter(raw);
    expect(raw.startsWith("---\n")).toBeTrue();
    expect(body.startsWith("---\n")).toBeFalse();
    expect(body.startsWith("<!-- AUTO-GENERATED")).toBeFalse();
    expect(body).not.toContain("AUTO-GENERATED by software-teams");
  });
});

type SpawnCall = { prompt: string };

const spawnCalls: SpawnCall[] = [];

function makeFakeProcess() {
  const stdoutListeners: Record<string, ((...args: unknown[]) => void)[]> = {};
  const procListeners: Record<string, ((...args: unknown[]) => void)[]> = {};
  const fakeProc = {
    stdout: {
      on(event: string, cb: (...args: unknown[]) => void) {
        stdoutListeners[event] = stdoutListeners[event] ?? [];
        stdoutListeners[event]!.push(cb);
      },
    },
    stdin: { write() {}, end() {} },
    on(event: string, cb: (...args: unknown[]) => void) {
      procListeners[event] = procListeners[event] ?? [];
      procListeners[event]!.push(cb);
    },
  };
  Promise.resolve().then(() => {
    const event = JSON.stringify({ type: "result", result: "done" });
    stdoutListeners["data"]?.forEach((cb) => cb(Buffer.from(`${event}\n`)));
    procListeners["close"]?.forEach((cb) => cb(0));
  });
  return fakeProc;
}

const realCp = require("child_process") as typeof import("child_process");
const realSpawn = realCp.spawn;

mock.module("child_process", () => ({
  ...realCp,
  execSync: (cmd: string) => (cmd === "which claude" ? "/usr/local/bin/claude\n" : ""),
  spawn: mock((bin: string, args: string[], opts: { cwd?: string }) => {
    const isClaude = bin.endsWith("claude") || bin.endsWith("claude.exe");
    if (!isClaude) return realSpawn(bin, args, opts as Parameters<typeof realSpawn>[2]);
    spawnCalls.push({ prompt: args[args.length - 1] ?? "" });
    return makeFakeProcess();
  }),
}));

const { runAgentTurn } = await import("../single-turn");

function makeEnvelope(agentId: string): NodeEnvelope {
  return {
    correlationId: "run-persona-001",
    agentId,
    status: "ok",
    input: { prompt: "Do the work.", context: null },
    result: { text: "" },
    artifacts: [],
  };
}

await runAgentTurn(makeEnvelope("software-teams-backend"));
const hasRealSpawnInterception = spawnCalls.length > 0;
spawnCalls.length = 0;

const TASK_MARKER = "## Task";

describe("runAgentTurn — null degrade preserved through real adapter (AC8)", () => {
  beforeEach(() => {
    spawnCalls.length = 0;
  });

  test.skipIf(!hasRealSpawnInterception)(
    "an unknown agentId degrades to a bare prompt — no persona prefix, not fatal",
    async () => {
      const result = await runAgentTurn(makeEnvelope("software-teams-does-not-exist"));
      const prompt = spawnCalls[0]!.prompt;
      expect(prompt.startsWith(TASK_MARKER)).toBeTrue();
      expect(prompt).not.toContain("\n\n---\n\n");
      expect(result.status).toBe("ok");
    },
  );

  test("unknown agentId still returns a well-formed ok envelope (degrade is non-fatal)", async () => {
    const result = await runAgentTurn(makeEnvelope("software-teams-does-not-exist"));
    expect(result.correlationId).toBe("run-persona-001");
    expect(result.agentId).toBe("software-teams-does-not-exist");
    expect(typeof result.result.text).toBe("string");
  });
});
