/**
 * AgentTeamsOrchestration component module.
 *
 * Parsing rules applied:
 * - YAML frontmatter provides `name`, `category`, `description`.
 * - `## Heading` boundaries delimit sections.
 * - Body trim: leading/trailing whitespace only; internal whitespace preserved.
 * - Inline `@ST:` references lifted into `requires` AND kept in body.
 */

import type { Component } from "../types";

const AgentTeamsOrchestration: Component = {
  name: "AgentTeamsOrchestration",
  category: "meta",
  description: "Agent Teams orchestration quick-reference",
  sections: {
    CorePattern: {
      name: "CorePattern",
      description: "Six-step orchestration pattern for Agent Teams",
      body: `1. **Pre-flight** — Read command spec, \`@ST:CodebaseContext\`, read state.yaml, set status to "executing". Read each task file's \`agent:\` frontmatter field so you know which specialist to spawn per task (see \`the AgentRouter component\`).
2. **Create Team** — \`TeamCreate(team_name: "{slug}-team")\` where \`{slug}\` is the \`current_plan.slug\` field from \`state.yaml\` (set by \`software-teams-planner\` at plan-write time). The literal \`{slug}-team\` pattern is the convention shared by both single-tier (§8) and three-tier (§3T.8) execution paths in \`commands/implement-plan.md\` — do not invent a different team-name format.
3. **Create Tasks** — TaskCreate per work unit, set \`addBlockedBy\` dependencies
4. **Spawn Teammates** — Task tool, one call per task. **Native spawn is the default** for both \`source: software-teams\` and \`source: claude-code\` agents (see \`AgentRouter.md\` §4):
    - **\`source: software-teams\`** (Software Teams framework specialists like \`software-teams-backend\`, \`software-teams-frontend\`, \`software-teams-qa-tester\`) — \`subagent_type: "{task.agent}"\` directly; Claude Code loads the spec from \`.claude/agents/{task.agent}.md\`, generated by \`software-teams sync-agents\` from \`agents/\`.
    - **\`source: claude-code\`** (user-added registered subagents like \`unity-ui-specialist\`) — \`subagent_type: "{task.agent}"\` directly; Claude Code loads the spec natively.
    - Verify the agent spec is registered before spawning. Check \`.claude/agents/{name}.md\` (project-local) or \`~/.claude/agents/{name}.md\` (user-global). Missing spec → downgrade to \`general-purpose\` (legacy fallback documented in \`AgentRouter.md\` §4) and record \`agent_downgrade:\` in the summary.
    - Include in prompt: team context and task assignments. Do NOT inject \`"You are {task.agent}. Read agents/..."\` preamble — Claude Code auto-loads the spec when spawned by name. **Scope tightly** — one task per spawn, exact file targets, capped exploration, short reports (<400 words). See \`AgentBase.md\` § Budget Discipline.
5. **Coordinate** — Automatic message delivery for results, TaskList to monitor, SendMessage to guide/unblock
6. **Cleanup** — shutdown_request to all → TeamDelete → set status "complete" → report (include which specialist ran which task and any downgrade events)`,
    },
    PeerCollaboration: {
      name: "PeerCollaboration",
      description: "Specialist-to-specialist collaboration + lead duties + experimental-feature caveats",
      body: `Teammates collaborate DIRECTLY, not only through the lead — this is what makes
a team better than one-shot fan-out.

### Specialist-to-specialist DMs

When a teammate hits a question another specialist owns — e.g. a
\`software-teams-programmer\` needs an interface decision from
\`software-teams-architect\`, or \`software-teams-frontend\` needs a contract shape
from \`software-teams-backend\` — DM that peer DIRECTLY by name with
\`SendMessage(to: "{peer-name}", ...)\` instead of stalling or round-tripping the
lead. Find peer names in the team config (\`~/.claude/teams/{team}/config.json\`,
\`members[].name\`). Keep working while you wait if you can; the reply arrives
automatically as a turn. The lead sees a brief summary of peer DMs via idle
notifications, so you do NOT need to CC the lead.

**Peer vs. lead — who to message:**
- **Peer** — a scoped technical question or handoff the peer owns: contracts,
  interfaces, shared types, "is X ready yet".
- **Lead** — blockers needing a decision or scope change, a missing dependency,
  or anything that should change the plan.

### Lead duties (the producer / team lead)

Beyond spawning teammates and committing results:
- **Monitor for lag.** Agent teams sometimes fail to mark a task complete, which
  blocks dependents. Periodically call \`TaskList\`; if a task sits
  \`in_progress\` with an idle owner and no recent progress, DM the owner to
  confirm or complete it (or reassign). Do NOT assume idle == done — idle just
  means waiting; check the task status.
- **Unblock.** If every available task is \`blockedBy\` open work, resolve or
  reprioritise the blockers so teammates aren't stuck.

### Experimental-feature caveats (handle these explicitly)

Agent teams are an experimental Claude Code feature. Two limitations matter:
- **Enablement.** Teams require \`CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS\` in
  settings/env. If \`TeamCreate\` is unavailable or fails, teams are not enabled —
  tell the user to add that flag, and fall back to single-agent mode for now.
- **No resume.** In-process teammates do NOT survive \`/resume\` or \`/rewind\`;
  the lead may end up messaging teammates that no longer exist. On resume, treat
  the team as gone: re-create it (\`TeamCreate\`) and respawn teammates from the
  still-current \`state.yaml\` / task board rather than messaging stale names.`,
    },
    TaskRoutingTable: {
      name: "TaskRoutingTable",
      description: "Fallback routing table when tasks have no agent pin",
      body: `**Primary source of truth:** each task's \`agent:\` frontmatter field, assigned
by \`software-teams-planner\` via \`AgentRouter\` at plan time. The table below is the
**fallback** used only when a task has no pin (legacy plans or empty
\`available_agents\`).

| Task Stack (fallback) | Agent(s) | Spawn Count |
|-----------|----------|-------------|
| PHP only | software-teams-backend | 1 |
| TS/React only | software-teams-frontend | 1 |
| Full-stack | software-teams-backend + software-teams-frontend | 2 |
| Config/docs | software-teams-backend (default) | 1 |

**Examples of honouring pins** (real values — not fallbacks):

| Task pin | Subagent type passed to Task tool |
|----------|-----------------------------------|
| \`agent: unity-specialist\` | \`unity-specialist\` |
| \`agent: unity-ui-specialist\` | \`unity-ui-specialist\` |
| \`agent: gameplay-programmer\` | \`gameplay-programmer\` |
| \`agent: qa-tester\` | \`qa-tester\` |
| \`agent: ue-gas-specialist\` | \`ue-gas-specialist\` |
| \`agent: godot-gdscript-specialist\` | \`godot-gdscript-specialist\` |`,
    },
    SpawnTemplates: {
      name: "SpawnTemplates",
      description: "Template for native and legacy agent spawn prompts",
      body: `### Native spawn (default — both \`source: software-teams\` and \`source: claude-code\`)

**Three-tier plans (default after T9/T10):** the spawn prompt passes ONLY the
per-agent slice and the SPEC sections cited in the slice's \`**Read first:**\`
line. Do NOT pass the full SPEC, the full ORCHESTRATION, or sibling slices.

\`\`\`
TEAM: {team-name}
ORCHESTRATION: {slug}.orchestration.md
TASK_FILE: {slug}.T{n}.md          # the per-agent slice — your only task brief
SPEC_SECTIONS: {sections cited in TASK_FILE's \`**Read first:**\` line}
WORKING_DIR: {working-directory}

Read your TASK_FILE for task details (objective, files, steps, verification,
done_when, and the \`agent_rationale\` explaining why you were picked for this
task). The slice's \`**Read first:**\` line names the SPEC sections you need —
read ONLY those sections, NOT the full spec or full orchestration. Do NOT
read sibling slices ({slug}.T{m}.md for m != n).

Also read the AgentBase component for the Software Teams base protocol.
If your spec has requires_components in frontmatter, batch-read them before
starting.

1. Implement using Edit tool (existing files) and Write tool (new files)
2. SendMessage to coordinator with structured return
3. Mark task completed via TaskUpdate

Report: files_modified, files_created, commits_pending.
No git commit (use commits_pending).
\`\`\`

**Single-tier (legacy) plans:** if no orchestration.md exists, pass \`PLAN:
{plan-path}\` and \`TASK_FILE: {task-file-path}\` — the agent reads the task
file plus the (smaller) plan index. Drop the \`SPEC_SECTIONS\` line.

Spawned via \`Agent(subagent_type="{task.agent}", mode="acceptEdits", ...)\`. Claude
Code auto-loads the agent spec from \`.claude/agents/{task.agent}.md\` when spawned
by name — do NOT inject \`"You are {task.agent}. Read agents/..."\`
preamble. Software Teams specialists land in \`.claude/agents/\` via \`software-teams sync-agents\`. See
\`the AgentRouter component\` §4 for the legacy fallback.`,
    },
    PostAgentOps: {
      name: "PostAgentOps",
      description: "Steps to perform after all specialist tasks complete",
      body: `After all specialist tasks complete:

1. **Collect** — Aggregate \`files_modified\`, \`files_created\`, \`commits_pending\` from all SendMessage results
2. **Execute commits** — \`git add\` + \`git commit\` for each \`commits_pending\` entry
3. **Record hashes** — Store real commit hashes in state.yaml
4. **Verify** — Confirm all \`files_modified\` and \`files_created\` are present in working tree`,
    },
    TeamLifecycle: {
      name: "TeamLifecycle",
      description: "Lifecycle stages for an Agent Team",
      body: `\`\`\`
TeamCreate → Spawn agents → Monitor (auto message delivery) →
Collect results → Deferred ops → shutdown_request → TeamDelete
\`\`\``,
    },
  },
  defaultOrder: [
    "CorePattern",
    "PeerCollaboration",
    "TaskRoutingTable",
    "SpawnTemplates",
    "PostAgentOps",
    "TeamLifecycle",
  ],
};

export default AgentTeamsOrchestration;
