/**
 * ComplexityRouter component module.
 *
 * Parsing rules applied:
 * - `## Heading` boundaries delimit sections (no YAML frontmatter).
 * - Body trim: leading/trailing whitespace only; internal whitespace preserved.
 * - Inline `@ST:` references lifted into `requires` AND kept in body.
 */

import type { Component } from "../types";

const ComplexityRouter: Component = {
  name: "ComplexityRouter",
  category: "meta",
  description:
    "Evaluates plan complexity and returns the routing decision for implement-plan",
  sections: {
    DecisionMatrix: {
      name: "DecisionMatrix",
      description: "Signals used to determine single-agent vs agent-teams mode",
      body: `Read the plan index file (frontmatter + task manifest table) and extract these signals:

| Signal | Simple | Complex |
|--------|--------|---------|
| Task count | ≤3 | >3 |
| Tech stacks | Single (PHP-only OR TS-only) | Mixed (PHP + TS/React) |
| Wave count | 1 (all tasks parallel or sequential) | >1 (multi-wave dependencies) |

**Routing rule:** If ANY signal is "Complex" → use Agent Teams mode. All signals must be "Simple" for single-agent mode.

**Override flags:**
- \`--team\` in command arguments → force Agent Teams mode
- \`--single\` in command arguments → force single-agent mode`,
    },
    Output: {
      name: "Output",
      description: "Routing decision output format",
      body: `After evaluation, set the routing decision:

\`\`\`yaml
mode: single-agent | agent-teams
primary_agent: software-teams-backend | software-teams-frontend  # based on tech stack
secondary_agents: []  # only populated in agent-teams mode
reasoning: "{why this mode was chosen}"
\`\`\``,
    },
    SingleAgentMode: {
      name: "SingleAgentMode",
      description: "How to spawn a single specialist agent for simple plans",
      body: `Spawn one specialist agent directly via Task tool, **natively by name**.

> **Three-tier plans (post-T9/T10):** when the plan has an \`orchestration.md\`
> artefact, single-agent mode loads SPEC + ORCHESTRATION as the **orchestrator
> brief** (the agent acts as its own orchestrator across the task graph). Each
> per-task spawn it makes downstream still loads ONLY the per-agent slice
> (\`{slug}.T{n}.md\`) plus the SPEC sections cited in the slice's
> \`**Read first:**\` line — never the full SPEC, never the full task list. See
> \`framework/commands/implement-plan.md\` Three-Tier Execution Loop.

> **Single-tier plans (legacy):** the primary agent loads the full
> \`{slug}.plan.md\` index and reads each \`{slug}.T{n}.md\` task file as it
> reaches it. No SPEC/ORCHESTRATION split.

**Pinning rule:** read \`primary_agent\` from the plan index frontmatter and the
matching \`source:\` from \`available_agents\`. Verify the agent spec is registered
with Claude Code:

- \`source: software-teams\` → check \`.claude/agents/{name}.md\` (generated by \`software-teams sync-agents\`
  from \`.software-teams/framework/agents/{name}.md\` or \`framework/agents/{name}.md\` in the
  self-hosting Software Teams repo)
- \`source: claude-code\` → check \`.claude/agents/{name}.md\` or
  \`~/.claude/agents/{name}.md\`

If unset or not found, fall back to \`general-purpose\` and record an
\`agent_downgrade:\` note in the summary. Never silently default to
\`general-purpose\` when a pin exists.
See \`the AgentRouter component\` §4 for full spawn rules.

### Native spawn (default — both \`source: software-teams\` and \`source: claude-code\`)

\`\`\`
Agent(
  subagent_type: "{plan.primary_agent}",   # e.g. software-teams-backend, software-teams-frontend, unity-specialist
  mode: "acceptEdits",                     # REQUIRED: scoped allowlist lives in .claude/settings.json
  name: "{plan.primary_agent}",
  prompt: "## Project Context
- Type: {project_type}
- Tech stack: {tech_stack}
- Quality gates: {quality_gates}
- Working directory: {cwd}

## Task
Execute all tasks in the plan sequentially. PLAN: {plan-path}.
For split plans (task_files in frontmatter), read each task file one at a time
from the file: field in state.yaml.
Report: files_modified, files_created, commits_pending."
)
\`\`\`

Claude Code loads the agent spec from \`.claude/agents/{plan.primary_agent}.md\`
automatically when spawned by name — do NOT inject identity preamble in the
prompt. Software Teams specialists are placed there by \`software-teams sync-agents\`, which converts
the canonical specs in \`framework/agents/software-teams-*.md\` to the Claude Code format.

No TeamCreate, no TaskCreate, no cross-agent coordination.

<!-- lint-allow: legacy-injection -->
### Legacy fallback (no pins)

When \`primary_agent\` is missing or empty (legacy plan with no AgentRouter
discovery), fall back to \`subagent_type: "general-purpose"\` and load the
software-teams-backend / software-teams-frontend spec inside the prompt as a last resort. See
\`AgentRouter.md\` §4 for the documented fallback pattern (lint-allowlisted).
<!-- /lint-allow -->`,
    },
    AgentTeamsMode: {
      name: "AgentTeamsMode",
      description: "How to run full Agent Teams orchestration for complex plans",
      body: `Follow full orchestration from \`the AgentTeamsOrchestration component\`:
TeamCreate → TaskCreate per plan task → spawn specialists per tech-stack routing → wave-based coordination → collect deferred ops → shutdown → TeamDelete.`,
    },
    Usage: {
      name: "Usage",
      description: "Tag usage and references",
      body: `\`\`\`
@ST:ComplexityRouter
\`\`\`

Referenced by implement-plan command stub. Evaluates at orchestration time, before any agents are spawned.`,
    },
  },
  defaultOrder: [
    "DecisionMatrix",
    "Output",
    "SingleAgentMode",
    "AgentTeamsMode",
    "Usage",
  ],
};

export default ComplexityRouter;
