import { existsSync, readFileSync } from "node:fs";

export type ConflictMode =
  | "overwrite"
  | "skip"
  | "error"
  | "preserve-user-owned";

export const AUTO_GENERATED_PREFIX = "<!-- AUTO-GENERATED by software-teams sync-agents";

function hasAutoGeneratedBanner(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf-8");
    const firstNonBlank =
      content.split("\n").find((l: string) => l.trim().length > 0) ?? "";
    return firstNonBlank.trim().startsWith(AUTO_GENERATED_PREFIX);
  } catch {
    return false;
  }
}

export interface ConvertAgentsResult {
  written: string[];
  unchanged: string[];
  skipped: string[];
  errors: { file: string; reason: string }[];
}

export function shouldWriteUnderConflict(
  outPath: string,
  mode: ConflictMode,
  result: ConvertAgentsResult,
): boolean {
  if (!existsSync(outPath)) return true;
  if (mode === "overwrite") return true;
  if (mode === "skip") {
    result.skipped.push(outPath);
    return false;
  }
  if (mode === "error") {
    result.errors.push({
      file: outPath,
      reason: "target file already exists and onConflict='error'",
    });
    return false;
  }
  // preserve-user-owned: overwrite only when we recognise our own banner.
  if (hasAutoGeneratedBanner(outPath)) return true;
  result.skipped.push(outPath);
  return false;
}

export async function writeIfChanged(outPath: string, rendered: string): Promise<boolean> {
  if (existsSync(outPath)) {
    const existing = await Bun.file(outPath).text();
    if (existing === rendered) return false;
  }
  await Bun.write(outPath, rendered);
  return true;
}
