import { stringify as stringifyYaml } from "yaml";
import { getComponent } from "../../components/resolve";
import type { AgentFrontmatter, ParsedAgentFile } from "./frontmatter";
import { buildOutputFrontmatter } from "./frontmatter";

const ST_TAG_RE = /@ST:([A-Za-z][A-Za-z0-9-]*)(?::([A-Za-z][A-Za-z0-9-]*))?/g;

function expandComponentTags(body: string): string {
  return body.replace(ST_TAG_RE, (_match, name, section) => {
    try {
      return getComponent(name, section);
    } catch (err) {
      throw new Error(
        `convert-agents: unresolved component tag '@ST:${name}${section ? `:${section}` : ""}': ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  });
}

export function renderAgentOutput(parsed: ParsedAgentFile, sourcePath: string): string {
  const fm = parsed.frontmatter as AgentFrontmatter;
  const outFm = buildOutputFrontmatter(fm);

  const yamlBody = stringifyYaml(outFm, { lineWidth: 0 }).trimEnd();
  const banner = `<!-- AUTO-GENERATED by software-teams sync-agents — edit agents/${fm.name}.md and re-run -->`;
  const footer = `Software Teams source: ${sourcePath}`;

  const body = expandComponentTags(
    parsed.body.replace(/^\s+/, "").replace(/\s+$/, ""),
  );

  return [
    "---",
    yamlBody,
    "---",
    "",
    banner,
    "",
    body,
    "",
    footer,
    "",
  ].join("\n");
}

export const CATALOGUE_BANNER =
  "<!-- AUTO-GENERATED by software-teams sync-agents — edit agents/*.md and templates/AGENTS.md.template (if used) and re-run -->";
export const RULES_BANNER =
  "<!-- AUTO-GENERATED by software-teams sync-agents — edit templates/RULES.md and re-run -->";

export const CATALOGUE_PREAMBLE =
  "These agents are spawned via `Task subagent_type=<name>`. Each agent's full spec is in `.claude/agents/<name>.md` (auto-generated from `agents/<name>.md`). See `RULES.md` for orchestration doctrine.";

export interface CatalogueEntry {
  name: string;
  model: string;
  description: string;
}

function escapeTableCell(value: string): string {
  return value.replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

export function renderCatalogue(entries: CatalogueEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const rows = sorted.map(
    (e) => `| ${e.name} | ${e.model} | ${escapeTableCell(e.description)} |`,
  );
  return [
    CATALOGUE_BANNER,
    "",
    "# Software Teams Agent Catalogue",
    "",
    CATALOGUE_PREAMBLE,
    "",
    "| Name | Model | Description |",
    "| ---- | ----- | ----------- |",
    ...rows,
    "",
  ].join("\n");
}
