import { describe, test, expect, afterEach } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, readdirSync } from "fs";
import { writeFile, readFile } from "node:fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { parse as parseYaml } from "yaml";
import { convertAgents, validateAgentFrontmatter } from "./convert-agents";
import { getComponent } from "../components/resolve";

let tempDirs: string[] = [];

function makeTempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "st-conv-"));
  tempDirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of tempDirs) {
    rmSync(dir, { recursive: true, force: true });
  }
  tempDirs = [];
});

const REPO_ROOT = join(import.meta.dir, "..", "..");
const REAL_SOURCE = join(REPO_ROOT, "agents");
const REAL_RULES_TEMPLATE = join(REPO_ROOT, "framework", "templates", "RULES.md");

/**
 * Build a fixture cwd with a real `agents/` + `framework/templates` tree by
 * symlinking. agents/ is the plugin-tree source-of-truth at the repo root;
 * templates/ still lives under framework/.
 */
async function makeFixtureCwd(): Promise<string> {
  const cwd = makeTempDir();
  // Symlink the real agents/ tree at the cwd root.
  await Bun.$`ln -s ${REAL_SOURCE} ${join(cwd, "agents")}`.quiet();
  // framework/templates lives under framework/, so we need the wrapper dir.
  const fwDir = join(cwd, "framework");
  mkdirSync(fwDir, { recursive: true });
  await Bun.$`ln -s ${join(REPO_ROOT, "framework", "templates")} ${join(fwDir, "templates")}`.quiet();
  return cwd;
}

function parseFrontmatter(content: string): { fm: Record<string, unknown>; body: string } {
  const m = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) throw new Error("no frontmatter in " + content.slice(0, 60));
  return { fm: (parseYaml(m[1]) ?? {}) as Record<string, unknown>, body: m[2] ?? "" };
}

describe("convertAgents — output shape", () => {
  test("output frontmatter contains exactly name, description, model, tools", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    expect(files.length).toBe(24);

    for (const file of files) {
      const content = await readFile(join(targetDir, file), "utf-8");
      const { fm } = parseFrontmatter(content);
      expect(Object.keys(fm).sort()).toEqual(["description", "model", "name", "tools"]);
      // Explicit no-leakage check.
      expect(fm.category).toBeUndefined();
      expect(fm.team).toBeUndefined();
      expect(fm.requires_components).toBeUndefined();
    }
  });

  test("AUTO-GENERATED banner is the first non-frontmatter line", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    for (const file of files) {
      const content = await readFile(join(targetDir, file), "utf-8");
      const { body } = parseFrontmatter(content);
      // Skip leading blank lines, take the first non-empty line.
      const firstLine = body.split("\n").find((l) => l.trim().length > 0);
      expect(firstLine).toMatch(/^<!-- AUTO-GENERATED by software-teams sync-agents/);
    }
  });

  test("tools array is sorted deterministically in output", async () => {
    const cwd = await makeFixtureCwd();
    await convertAgents({ cwd });
    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    for (const file of files) {
      const content = await readFile(join(targetDir, file), "utf-8");
      const { fm } = parseFrontmatter(content);
      const tools = fm.tools as string[];
      const sorted = [...tools].sort((a, b) => a.localeCompare(b));
      expect(tools).toEqual(sorted);
    }
  });
});

describe("convertAgents — idempotence", () => {
  test("running twice produces byte-identical output", async () => {
    const cwd = await makeFixtureCwd();
    const r1 = await convertAgents({ cwd });
    expect(r1.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files1 = readdirSync(targetDir).sort();
    const snapshot1: Record<string, string> = {};
    for (const f of files1) {
      snapshot1[f] = await readFile(join(targetDir, f), "utf-8");
    }
    const agentsMd1 = await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8");
    const rulesMd1 = await readFile(join(cwd, ".claude", "RULES.md"), "utf-8");

    const r2 = await convertAgents({ cwd });
    expect(r2.errors).toEqual([]);

    const files2 = readdirSync(targetDir).sort();
    expect(files2).toEqual(files1);
    for (const f of files2) {
      const content = await readFile(join(targetDir, f), "utf-8");
      expect(content).toBe(snapshot1[f]);
    }
    expect(await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8")).toBe(agentsMd1);
    expect(await readFile(join(cwd, ".claude", "RULES.md"), "utf-8")).toBe(rulesMd1);
  });
});

describe("convertAgents — dryRun", () => {
  test("dryRun writes no files but populates result.written", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd, dryRun: true });
    expect(result.errors).toEqual([]);
    // 24 agents + AGENTS.md + RULES.md
    expect(result.written.length).toBe(26);

    // Nothing on disk under .claude
    const claudeDir = join(cwd, ".claude");
    let exists = true;
    try {
      readdirSync(claudeDir);
    } catch {
      exists = false;
    }
    expect(exists).toBe(false);
  });
});

describe("validateAgentFrontmatter", () => {
  test("throws with file path and missing field on mangled fixture", async () => {
    const cwd = makeTempDir();
    const sourceDir = join(cwd, "agents");
    mkdirSync(sourceDir, { recursive: true });
    // Missing `model:` field deliberately
    const mangledPath = join(sourceDir, "software-teams-broken.md");
    await writeFile(
      mangledPath,
      `---
name: software-teams-broken
description: Test fixture missing model field
tools: [Read]
---

# Body content
`,
    );

    expect(() => {
      const content = `name: software-teams-broken
description: x
tools: [Read]
`;
      const fm = parseYaml(content) as Record<string, unknown>;
      validateAgentFrontmatter(fm, mangledPath);
    }).toThrow(/software-teams-broken\.md/);

    // Also exercise via convertAgents end-to-end.
    const result = await convertAgents({ cwd, sourceDir });
    expect(result.errors.length).toBeGreaterThan(0);
    const err = result.errors.find((e) => e.file === mangledPath);
    expect(err).toBeDefined();
    expect(err!.reason).toContain("model");
    expect(err!.reason).toContain(mangledPath);
  });

  test("passes for a well-formed frontmatter", () => {
    const fm = {
      name: "software-teams-x",
      description: "ok",
      model: "haiku",
      tools: ["Read", "Bash"],
    };
    expect(() => validateAgentFrontmatter(fm, "/tmp/foo.md")).not.toThrow();
  });

  test("flags empty tools array", () => {
    const fm = { name: "software-teams-x", description: "ok", model: "haiku", tools: [] };
    expect(() => validateAgentFrontmatter(fm, "/tmp/foo.md")).toThrow(/tools/);
  });
});

describe("convertAgents — AGENTS.md catalogue", () => {
  test("lists all 24 agents alphabetically with correct model column", async () => {
    const cwd = await makeFixtureCwd();
    await convertAgents({ cwd });

    const agentsMd = await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8");
    expect(agentsMd).toMatch(/^<!-- AUTO-GENERATED by software-teams sync-agents/);

    // Extract data rows (skip header + separator).
    const lines = agentsMd.split("\n");
    const rowLines = lines.filter((l) => /^\| software-teams-/.test(l));
    expect(rowLines.length).toBe(24);

    // Names should be alphabetical.
    const names = rowLines.map((l) => l.split("|")[1].trim());
    const sorted = [...names].sort((a, b) => a.localeCompare(b));
    expect(names).toEqual(sorted);

    // Cross-reference each row's model with the source spec frontmatter.
    for (const row of rowLines) {
      const cells = row.split("|").map((c) => c.trim());
      // ['', name, model, description, '']
      const name = cells[1];
      const model = cells[2];
      const sourcePath = join(REAL_SOURCE, `${name}.md`);
      const src = await readFile(sourcePath, "utf-8");
      const { fm } = parseFrontmatter(src);
      expect(model).toBe(fm.model as string);
    }
  });
});

describe("convertAgents — RULES.md", () => {
  test("RULES.md content equals the template body modulo banner", async () => {
    const cwd = await makeFixtureCwd();
    await convertAgents({ cwd });

    const generated = await readFile(join(cwd, ".claude", "RULES.md"), "utf-8");
    const template = await readFile(REAL_RULES_TEMPLATE, "utf-8");

    expect(generated.startsWith("<!-- AUTO-GENERATED by software-teams sync-agents")).toBe(true);

    // Strip the banner + leading blank line from generated.
    const stripped = generated.replace(/^<!--[^\n]*-->\n+/, "").trimEnd();
    expect(stripped).toBe(template.trimEnd());
  });
});

describe("convertAgents — wave-1 rebrand glob verification", () => {
  test("glob discovers exactly 24 files matching software-teams-*.md", async () => {
    const sourceDir = REAL_SOURCE;
    const files = readdirSync(sourceDir).filter((f) => /^software-teams-.+\.md$/.test(f));
    expect(files.length).toBe(24);
    expect(files.every((f) => f.startsWith("software-teams-"))).toBe(true);
  });

  test("glob NEVER matches old jdi-*.md pattern (regression guard)", async () => {
    const sourceDir = REAL_SOURCE;
    const jdiFiles = readdirSync(sourceDir).filter((f) => /^jdi-.+\.md$/.test(f));
    expect(jdiFiles.length).toBe(0);
  });

  test("convertAgents produces 24 agent entries (glob success)", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const agentFiles = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    expect(agentFiles.length).toBe(24);

    // Spot-check that names are correctly renamed
    expect(agentFiles.some((f) => f === "software-teams-planner.md")).toBe(true);
    expect(agentFiles.some((f) => f === "software-teams-qa-tester.md")).toBe(true);
    expect(agentFiles.some((f) => f === "software-teams-backend.md")).toBe(true);
    expect(agentFiles.some((f) => /^software-teams-/.test(f))).toBe(true);
    expect(agentFiles.some((f) => /^jdi-/.test(f))).toBe(false);
  });
});

describe("convertAgents — wave 4 round-trip (@ST: expansion)", () => {
  /**
   * Test 1: Synthetic happy path.
   * A spec containing @ST:Verify:Task should expand to the resolved body
   * and produce zero literal @ST: tags in the output.
   */
  test("synthetic happy path: @ST:Verify:Task expands and no literal tags remain", async () => {
    const cwd = makeTempDir();
    const sourceDir = join(cwd, "agents");
    mkdirSync(sourceDir, { recursive: true });

    // Create a synthetic agent spec with an @ST: tag
    const syntheticPath = join(sourceDir, "software-teams-wave4-test.md");
    const syntheticContent = `---
name: software-teams-wave4-test
description: Wave 4 round-trip test agent
model: test-model
tools: [Read, Bash]
---

# Test Agent

This agent uses the component expansion tag:
@ST:Verify:Task

More content here.
`;
    await writeFile(syntheticPath, syntheticContent);

    // Also symlink templates to avoid errors
    const fwDir = join(cwd, "framework");
    mkdirSync(fwDir, { recursive: true });
    await Bun.$`ln -s ${join(REPO_ROOT, "framework", "templates")} ${join(fwDir, "templates")}`.quiet();

    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetPath = join(cwd, ".claude", "agents", "software-teams-wave4-test.md");
    const content = await readFile(targetPath, "utf-8");
    const { body } = parseFrontmatter(content);

    // The resolved body should NOT contain a literal @ST:Verify:Task tag
    expect(body).not.toContain("@ST:Verify:Task");
    // The resolved body SHOULD contain content from the Verify:Task section
    expect(body.length).toBeGreaterThan(100); // Verify:Task has substantial content
  });

  /**
   * Test 2: Synthetic broken ref.
   * A spec containing @ST:DoesNotExist should cause convertAgents to throw
   * with a clear error message including the component name.
   */
  test("synthetic broken ref: @ST:DoesNotExist throws with clear error", async () => {
    const cwd = makeTempDir();
    const sourceDir = join(cwd, "agents");
    mkdirSync(sourceDir, { recursive: true });

    const syntheticPath = join(sourceDir, "software-teams-broken-ref.md");
    const syntheticContent = `---
name: software-teams-broken-ref
description: Broken reference test
model: test-model
tools: [Read]
---

# Test Agent

This references a component that does not exist:
@ST:DoesNotExist

End.
`;
    await writeFile(syntheticPath, syntheticContent);

    // Setup minimal framework
    const fwDir = join(cwd, "framework");
    mkdirSync(fwDir, { recursive: true });
    await Bun.$`ln -s ${join(REPO_ROOT, "framework", "templates")} ${join(fwDir, "templates")}`.quiet();

    const result = await convertAgents({ cwd });
    // Should have an error for the broken ref
    expect(result.errors.length).toBeGreaterThan(0);
    const brokenErr = result.errors.find((e) => e.file === syntheticPath);
    expect(brokenErr).toBeDefined();
    expect(brokenErr!.reason).toContain("DoesNotExist");
  });

  /**
   * Test 3: Idempotency.
   * Running convertAgents() twice in a row on the same input should produce
   * byte-identical output (including all generated files).
   */
  test("idempotency: two sequential runs produce byte-identical output", async () => {
    const cwd = await makeFixtureCwd();

    // First run
    const r1 = await convertAgents({ cwd });
    expect(r1.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const snapshot1: Record<string, string> = {};
    const files1 = readdirSync(targetDir).sort();
    for (const f of files1) {
      snapshot1[f] = await readFile(join(targetDir, f), "utf-8");
    }
    const agentsMd1 = await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8");

    // Second run
    const r2 = await convertAgents({ cwd });
    expect(r2.errors).toEqual([]);

    const files2 = readdirSync(targetDir).sort();
    expect(files2).toEqual(files1);
    for (const f of files2) {
      const content = await readFile(join(targetDir, f), "utf-8");
      expect(content).toBe(snapshot1[f]);
    }
    expect(await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8")).toBe(agentsMd1);
  });

  /**
   * Test 4: Code-block preservation.
   * T11 should have protected backtick-enclosed <JDI: strings from rename.
   * This test verifies that a synthetic input containing `<JDI:OldThing />`
   * inside inline backticks survives round-trip through expandComponentTags
   * unchanged (since expandComponentTags only matches @ST:, not <JDI:).
   */
  test("code-block preservation: inline backtick <JDI: survives unchanged", async () => {
    const cwd = makeTempDir();
    const sourceDir = join(cwd, "agents");
    mkdirSync(sourceDir, { recursive: true });

    const syntheticPath = join(sourceDir, "software-teams-codeblock-test.md");
    const syntheticContent = `---
name: software-teams-codeblock-test
description: Code block preservation test
model: test-model
tools: [Read]
---

# Test Agent

This is an example of the old syntax (documentation):
\`\`\`
@ST:Verify:Task  <!-- This is the new syntax -->
<JDI:Verify /> <!-- This is the old syntax, inside backticks -->
\`\`\`

And inline: \`<JDI:OldThing />\` stays as-is.

End.
`;
    await writeFile(syntheticPath, syntheticContent);

    const fwDir = join(cwd, "framework");
    mkdirSync(fwDir, { recursive: true });
    await Bun.$`ln -s ${join(REPO_ROOT, "framework", "templates")} ${join(fwDir, "templates")}`.quiet();

    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetPath = join(cwd, ".claude", "agents", "software-teams-codeblock-test.md");
    const content = await readFile(targetPath, "utf-8");
    const { body } = parseFrontmatter(content);

    // The inline-backtick `<JDI:OldThing />` should be preserved exactly
    expect(body).toContain("`<JDI:OldThing />`");
    // The fenced block should be preserved with both syntaxes
    expect(body).toContain("<JDI:Verify />");
    // @ST:Verify:Task in the fenced block should NOT be expanded (it's inside backticks from T11)
    // Actually, our expandComponentTags runs on the already-protected body from T11,
    // so the @ST: tag inside the fenced block would still match the regex. Let's just verify
    // the inline backtick is preserved.
    expect(body).toContain("`<JDI:OldThing />`");
  });

  /**
   * Test 5: Live-tree snapshot.
   * Load the real framework/agents/software-teams-planner.md, run convertAgents,
   * and snapshot the resolved output. This verifies that the inlining mechanism
   * produces stable, expected output for a real agent.
   */
  test("live-tree snapshot: software-teams-planner output matches committed snapshot", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetPath = join(cwd, ".claude", "agents", "software-teams-planner.md");
    const content = await readFile(targetPath, "utf-8");

    // Use Bun's built-in snapshot testing
    expect(content).toMatchSnapshot();
  });
});

describe("Component tag audit — T1 + T2 regression guards", () => {
  /**
   * Test 2: Tag-resolution coverage.
   * Walk framework/**\/*.md, extract every @ST: tag via the canonical regex,
   * and assert getComponent(name, section) resolves cleanly for each.
   * Skip tags inside backticks or fenced code blocks (matching T2's protection).
   */
  test("T2 regression guard: every @ST: tag in framework/ resolves via getComponent", async () => {
    const globPattern = new Bun.Glob("**/*.md");
    const frameworkDir = join(REPO_ROOT, "framework");

    // Canonical @ST: regex (must match T2's protection logic)
    const tagRegex = /@ST:([A-Za-z][A-Za-z0-9-]*)(?::([A-Za-z][A-Za-z0-9-]*))?/g;

    // Track all discovered tags for diagnostics
    const discoveredTags: Array<{ component: string; section: string | null; file: string; line: number }> = [];

    for await (const file of globPattern.scan(frameworkDir)) {
      const fullPath = join(frameworkDir, file);
      const content = await readFile(fullPath, "utf-8");

      // Remove backtick-protected regions: inline backticks and fenced code blocks
      let cleanContent = content;

      // Remove inline backticks (e.g., `@ST:...`)
      cleanContent = cleanContent.replace(/`[^`]*`/g, "");

      // Remove fenced code blocks (e.g., ``` ... ```)
      cleanContent = cleanContent.replace(/```[\s\S]*?```/g, "");
      cleanContent = cleanContent.replace(/~~~[\s\S]*?~~~/g, "");

      // Now extract and validate @ST: tags
      const lines = cleanContent.split("\n");
      let lineNum = 0;
      for (const line of lines) {
        lineNum++;
        let match;
        while ((match = tagRegex.exec(line)) !== null) {
          const componentName = match[1];
          const sectionName = match[2] || null;

          discoveredTags.push({
            component: componentName,
            section: sectionName,
            file,
            line: lineNum,
          });

          // Attempt to resolve via getComponent
          expect(() => {
            if (sectionName) {
              getComponent(componentName, sectionName);
            } else {
              getComponent(componentName);
            }
          }).not.toThrow(
            `Failed to resolve @ST:${componentName}${sectionName ? `:${sectionName}` : ""} in ${file}:${lineNum}`,
          );
        }
      }
    }

    // Sanity check: we should have found some tags
    expect(discoveredTags.length).toBeGreaterThan(0);
  });

  /**
   * Test 3: Whole-component tag budget.
   * Count @ST:Name tags (no :Section) in framework/**\/*.md, excluding
   * backtick/code-block protected regions. Assert the count is <= 25
   * (a soft regression buffer above the T2 target of ~14).
   */
  test("T2 regression guard: whole-component @ST: tag count <= 25", async () => {
    const globPattern = new Bun.Glob("**/*.md");
    const frameworkDir = join(REPO_ROOT, "framework");

    // Regex to match only whole-component tags (no :Section)
    const wholeComponentTagRegex = /@ST:([A-Za-z][A-Za-z0-9-]*)(?!:[A-Za-z][A-Za-z0-9-]*)/g;

    let wholeComponentCount = 0;

    for await (const file of globPattern.scan(frameworkDir)) {
      const fullPath = join(frameworkDir, file);
      const content = await readFile(fullPath, "utf-8");

      // Remove backtick-protected regions
      let cleanContent = content;
      cleanContent = cleanContent.replace(/`[^`]*`/g, "");
      cleanContent = cleanContent.replace(/```[\s\S]*?```/g, "");
      cleanContent = cleanContent.replace(/~~~[\s\S]*?~~~/g, "");

      // Count whole-component matches
      while (wholeComponentTagRegex.exec(cleanContent) !== null) {
        wholeComponentCount++;
      }
    }

    expect(
      wholeComponentCount,
      `Found ${wholeComponentCount} whole-component @ST: tags; T2's soft regression budget allows <= 25 (target ~14)`,
    ).toBeLessThanOrEqual(25);
  });
});
