import { describe, test, expect, afterEach } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, readdirSync } from "fs";
import { writeFile, readFile } from "node:fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { parse as parseYaml } from "yaml";
import { convertAgents, validateAgentFrontmatter } from "./convert-agents";

let tempDirs: string[] = [];

function makeTempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "st-conv-"));
  tempDirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of tempDirs) {
    rmSync(dir, { recursive: true, force: true });
  }
  tempDirs = [];
});

const REPO_ROOT = join(import.meta.dir, "..", "..");
const REAL_SOURCE = join(REPO_ROOT, "framework", "agents");
const REAL_RULES_TEMPLATE = join(REPO_ROOT, "framework", "templates", "RULES.md");

/**
 * Build a fixture cwd with a real `framework/agents` + `framework/templates`
 * tree by symlinking — keeps the converter exercising the real specs while
 * giving every test an isolated `.claude/` to write into.
 */
async function makeFixtureCwd(): Promise<string> {
  const cwd = makeTempDir();
  // Use symlink to the real framework/ so the converter sees real specs.
  const fwDir = join(cwd, "framework");
  mkdirSync(fwDir, { recursive: true });
  // Symlink agents and templates separately.
  await Bun.$`ln -s ${REAL_SOURCE} ${join(fwDir, "agents")}`.quiet();
  await Bun.$`ln -s ${join(REPO_ROOT, "framework", "templates")} ${join(fwDir, "templates")}`.quiet();
  return cwd;
}

function parseFrontmatter(content: string): { fm: Record<string, unknown>; body: string } {
  const m = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) throw new Error("no frontmatter in " + content.slice(0, 60));
  return { fm: (parseYaml(m[1]) ?? {}) as Record<string, unknown>, body: m[2] ?? "" };
}

describe("convertAgents — output shape", () => {
  test("output frontmatter contains exactly name, description, model, tools", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    expect(files.length).toBe(24);

    for (const file of files) {
      const content = await readFile(join(targetDir, file), "utf-8");
      const { fm } = parseFrontmatter(content);
      expect(Object.keys(fm).sort()).toEqual(["description", "model", "name", "tools"]);
      // Explicit no-leakage check.
      expect(fm.category).toBeUndefined();
      expect(fm.team).toBeUndefined();
      expect(fm.requires_components).toBeUndefined();
    }
  });

  test("AUTO-GENERATED banner is the first non-frontmatter line", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    for (const file of files) {
      const content = await readFile(join(targetDir, file), "utf-8");
      const { body } = parseFrontmatter(content);
      // Skip leading blank lines, take the first non-empty line.
      const firstLine = body.split("\n").find((l) => l.trim().length > 0);
      expect(firstLine).toMatch(/^<!-- AUTO-GENERATED by software-teams sync-agents/);
    }
  });

  test("tools array is sorted deterministically in output", async () => {
    const cwd = await makeFixtureCwd();
    await convertAgents({ cwd });
    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    for (const file of files) {
      const content = await readFile(join(targetDir, file), "utf-8");
      const { fm } = parseFrontmatter(content);
      const tools = fm.tools as string[];
      const sorted = [...tools].sort((a, b) => a.localeCompare(b));
      expect(tools).toEqual(sorted);
    }
  });
});

describe("convertAgents — idempotence", () => {
  test("running twice produces byte-identical output", async () => {
    const cwd = await makeFixtureCwd();
    const r1 = await convertAgents({ cwd });
    expect(r1.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files1 = readdirSync(targetDir).sort();
    const snapshot1: Record<string, string> = {};
    for (const f of files1) {
      snapshot1[f] = await readFile(join(targetDir, f), "utf-8");
    }
    const agentsMd1 = await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8");
    const rulesMd1 = await readFile(join(cwd, ".claude", "RULES.md"), "utf-8");

    const r2 = await convertAgents({ cwd });
    expect(r2.errors).toEqual([]);

    const files2 = readdirSync(targetDir).sort();
    expect(files2).toEqual(files1);
    for (const f of files2) {
      const content = await readFile(join(targetDir, f), "utf-8");
      expect(content).toBe(snapshot1[f]);
    }
    expect(await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8")).toBe(agentsMd1);
    expect(await readFile(join(cwd, ".claude", "RULES.md"), "utf-8")).toBe(rulesMd1);
  });
});

describe("convertAgents — dryRun", () => {
  test("dryRun writes no files but populates result.written", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd, dryRun: true });
    expect(result.errors).toEqual([]);
    // 24 agents + AGENTS.md + RULES.md
    expect(result.written.length).toBe(26);

    // Nothing on disk under .claude
    const claudeDir = join(cwd, ".claude");
    let exists = true;
    try {
      readdirSync(claudeDir);
    } catch {
      exists = false;
    }
    expect(exists).toBe(false);
  });
});

describe("validateAgentFrontmatter", () => {
  test("throws with file path and missing field on mangled fixture", async () => {
    const cwd = makeTempDir();
    const sourceDir = join(cwd, "framework", "agents");
    mkdirSync(sourceDir, { recursive: true });
    // Missing `model:` field deliberately
    const mangledPath = join(sourceDir, "software-teams-broken.md");
    await writeFile(
      mangledPath,
      `---
name: software-teams-broken
description: Test fixture missing model field
tools: [Read]
---

# Body content
`,
    );

    expect(() => {
      const content = `name: software-teams-broken
description: x
tools: [Read]
`;
      const fm = parseYaml(content) as Record<string, unknown>;
      validateAgentFrontmatter(fm, mangledPath);
    }).toThrow(/software-teams-broken\.md/);

    // Also exercise via convertAgents end-to-end.
    const result = await convertAgents({ cwd, sourceDir });
    expect(result.errors.length).toBeGreaterThan(0);
    const err = result.errors.find((e) => e.file === mangledPath);
    expect(err).toBeDefined();
    expect(err!.reason).toContain("model");
    expect(err!.reason).toContain(mangledPath);
  });

  test("passes for a well-formed frontmatter", () => {
    const fm = {
      name: "software-teams-x",
      description: "ok",
      model: "haiku",
      tools: ["Read", "Bash"],
    };
    expect(() => validateAgentFrontmatter(fm, "/tmp/foo.md")).not.toThrow();
  });

  test("flags empty tools array", () => {
    const fm = { name: "software-teams-x", description: "ok", model: "haiku", tools: [] };
    expect(() => validateAgentFrontmatter(fm, "/tmp/foo.md")).toThrow(/tools/);
  });
});

describe("convertAgents — AGENTS.md catalogue", () => {
  test("lists all 24 agents alphabetically with correct model column", async () => {
    const cwd = await makeFixtureCwd();
    await convertAgents({ cwd });

    const agentsMd = await readFile(join(cwd, ".claude", "AGENTS.md"), "utf-8");
    expect(agentsMd).toMatch(/^<!-- AUTO-GENERATED by software-teams sync-agents/);

    // Extract data rows (skip header + separator).
    const lines = agentsMd.split("\n");
    const rowLines = lines.filter((l) => /^\| software-teams-/.test(l));
    expect(rowLines.length).toBe(24);

    // Names should be alphabetical.
    const names = rowLines.map((l) => l.split("|")[1].trim());
    const sorted = [...names].sort((a, b) => a.localeCompare(b));
    expect(names).toEqual(sorted);

    // Cross-reference each row's model with the source spec frontmatter.
    for (const row of rowLines) {
      const cells = row.split("|").map((c) => c.trim());
      // ['', name, model, description, '']
      const name = cells[1];
      const model = cells[2];
      const sourcePath = join(REAL_SOURCE, `${name}.md`);
      const src = await readFile(sourcePath, "utf-8");
      const { fm } = parseFrontmatter(src);
      expect(model).toBe(fm.model as string);
    }
  });
});

describe("convertAgents — RULES.md", () => {
  test("RULES.md content equals the template body modulo banner", async () => {
    const cwd = await makeFixtureCwd();
    await convertAgents({ cwd });

    const generated = await readFile(join(cwd, ".claude", "RULES.md"), "utf-8");
    const template = await readFile(REAL_RULES_TEMPLATE, "utf-8");

    expect(generated.startsWith("<!-- AUTO-GENERATED by software-teams sync-agents")).toBe(true);

    // Strip the banner + leading blank line from generated.
    const stripped = generated.replace(/^<!--[^\n]*-->\n+/, "").trimEnd();
    expect(stripped).toBe(template.trimEnd());
  });
});

describe("convertAgents — wave-1 rebrand glob verification", () => {
  test("glob discovers exactly 24 files matching software-teams-*.md", async () => {
    const sourceDir = REAL_SOURCE;
    const files = readdirSync(sourceDir).filter((f) => /^software-teams-.+\.md$/.test(f));
    expect(files.length).toBe(24);
    expect(files.every((f) => f.startsWith("software-teams-"))).toBe(true);
  });

  test("glob NEVER matches old jdi-*.md pattern (regression guard)", async () => {
    const sourceDir = REAL_SOURCE;
    const jdiFiles = readdirSync(sourceDir).filter((f) => /^jdi-.+\.md$/.test(f));
    expect(jdiFiles.length).toBe(0);
  });

  test("convertAgents produces 24 agent entries (glob success)", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const agentFiles = readdirSync(targetDir).filter((f) => f.endsWith(".md"));
    expect(agentFiles.length).toBe(24);

    // Spot-check that names are correctly renamed
    expect(agentFiles.some((f) => f === "software-teams-planner.md")).toBe(true);
    expect(agentFiles.some((f) => f === "software-teams-qa-tester.md")).toBe(true);
    expect(agentFiles.some((f) => f === "software-teams-backend.md")).toBe(true);
    expect(agentFiles.some((f) => /^software-teams-/.test(f))).toBe(true);
    expect(agentFiles.some((f) => /^jdi-/.test(f))).toBe(false);
  });
});
