/**
 * Smoke tests for the generated `.claude/agents/` artefacts produced by
 * `convertAgents()` (T5 + wave-2 native-spawn migration).
 *
 * Validates the SHAPE of the generated artefacts end-to-end:
 *   - Each agent file in `.claude/agents/` parses as valid frontmatter +
 *     non-empty body, with the AUTO-GENERATED banner as the first non-frontmatter line.
 *   - The catalogue `AGENTS.md` parses with a markdown table of 24 rows.
 *   - `RULES.md` exists, is non-empty, and starts with the AUTO-GENERATED banner.
 *
 * Distinct from `convert-agents.test.ts` which exercises converter internals;
 * this file is the wave-2 audit of the artefact contract that downstream
 * Claude Code subagent registration depends on.
 */
import { describe, test, expect, afterEach } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parse as parseYaml } from "yaml";
import { convertAgents } from "./convert-agents";

let tempDirs: string[] = [];

function makeTempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "st-conv-smoke-"));
  tempDirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of tempDirs) {
    rmSync(dir, { recursive: true, force: true });
  }
  tempDirs = [];
});

const REPO_ROOT = join(import.meta.dir, "..", "..");
const REAL_FRAMEWORK = join(REPO_ROOT, "framework");
// Plugin tree (agents/) is now at the repo root; templates/ still under framework/.
const REAL_AGENTS = join(REPO_ROOT, "agents");
const REAL_TEMPLATES = join(REAL_FRAMEWORK, "templates");

/**
 * Build an isolated cwd that exposes the real plugin tree + framework/templates
 * via symlinks so the converter exercises real specs while writing to a temp
 * `.claude/`.
 */
async function makeFixtureCwd(): Promise<string> {
  const cwd = makeTempDir();
  await Bun.$`ln -s ${REAL_AGENTS} ${join(cwd, "agents")}`.quiet();
  const fwDir = join(cwd, "framework");
  mkdirSync(fwDir, { recursive: true });
  await Bun.$`ln -s ${REAL_TEMPLATES} ${join(fwDir, "templates")}`.quiet();
  return cwd;
}

function parseFrontmatter(content: string): { fm: Record<string, unknown>; body: string } {
  const m = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) throw new Error("no frontmatter — content begins: " + content.slice(0, 80));
  return { fm: (parseYaml(m[1]) ?? {}) as Record<string, unknown>, body: m[2] ?? "" };
}

describe("convertAgents — generated .claude/agents/ artefact shape", () => {
  test("each output file has frontmatter (name, description, model, tools), AUTO-GENERATED banner first, non-empty body", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const targetDir = join(cwd, ".claude", "agents");
    const files = readdirSync(targetDir).filter((f) => f.endsWith(".md")).sort();
    expect(files.length).toBe(24);

    for (const file of files) {
      const fullPath = join(targetDir, file);
      const content = await readFile(fullPath, "utf-8");
      const { fm, body } = parseFrontmatter(content);

      // Required frontmatter fields are present and well-typed.
      expect(typeof fm.name, `${file}: name`).toBe("string");
      expect((fm.name as string).length).toBeGreaterThan(0);

      expect(typeof fm.description, `${file}: description`).toBe("string");
      expect((fm.description as string).length).toBeGreaterThan(0);

      expect(typeof fm.model, `${file}: model`).toBe("string");
      expect(["opus", "sonnet", "haiku"]).toContain(fm.model as string);

      expect(Array.isArray(fm.tools), `${file}: tools must be an array`).toBe(true);
      expect((fm.tools as unknown[]).length).toBeGreaterThan(0);
      for (const tool of fm.tools as unknown[]) {
        expect(typeof tool, `${file}: each tool must be a string`).toBe("string");
      }

      // AUTO-GENERATED banner is the first non-empty line of the body.
      const firstLine = body.split("\n").find((l) => l.trim().length > 0);
      expect(firstLine, `${file}: missing first non-empty body line`).toBeDefined();
      expect(firstLine).toMatch(/^<!--\s*AUTO-GENERATED by software-teams sync-agents/i);

      // Body has substantive content beyond the banner alone.
      const bodyMinusBanner = body
        .split("\n")
        .filter((l) => !/^<!--/.test(l.trim()))
        .join("\n")
        .trim();
      expect(bodyMinusBanner.length, `${file}: body is empty after stripping banner`).toBeGreaterThan(0);
    }
  });

  test("AGENTS.md catalogue is a markdown table with exactly 24 data rows", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const agentsMdPath = join(cwd, ".claude", "AGENTS.md");
    expect(statSync(agentsMdPath).size, "AGENTS.md must be non-empty").toBeGreaterThan(0);

    const content = await readFile(agentsMdPath, "utf-8");

    // Banner is the first non-empty line.
    const firstLine = content.split("\n").find((l) => l.trim().length > 0);
    expect(firstLine).toMatch(/^<!--\s*AUTO-GENERATED by software-teams sync-agents/i);

    // Markdown table: header line, separator line, then 24 data rows.
    const lines = content.split("\n");
    const headerIdx = lines.findIndex((l) => /^\|\s*[A-Za-z]/.test(l));
    expect(headerIdx, "AGENTS.md must contain a markdown table header").toBeGreaterThan(-1);

    const separatorLine = lines[headerIdx + 1] ?? "";
    expect(/^\|[\s:|-]+\|$/.test(separatorLine.trim()), "AGENTS.md table must have a separator row").toBe(true);

    const dataRows = lines.slice(headerIdx + 2).filter((l) => /^\|\s*software-teams-/.test(l));
    expect(dataRows.length, "expected exactly 24 software-teams-* data rows in AGENTS.md").toBe(24);

    // Every row's first cell is a software-teams-* name.
    for (const row of dataRows) {
      const cells = row.split("|").map((c) => c.trim());
      const name = cells[1] ?? "";
      expect(/^software-teams-[a-z][a-z0-9-]*$/.test(name), `bad agent name in catalogue row: '${name}'`).toBe(true);
    }
  });

  test("RULES.md exists, has the AUTO-GENERATED banner, and is non-empty", async () => {
    const cwd = await makeFixtureCwd();
    const result = await convertAgents({ cwd });
    expect(result.errors).toEqual([]);

    const rulesPath = join(cwd, ".claude", "RULES.md");
    const stat = statSync(rulesPath);
    expect(stat.size, "RULES.md must be non-empty").toBeGreaterThan(0);

    const content = await readFile(rulesPath, "utf-8");
    const firstLine = content.split("\n").find((l) => l.trim().length > 0);
    expect(firstLine).toMatch(/^<!--\s*AUTO-GENERATED by software-teams sync-agents/i);

    // Strip banner; ensure substantive body remains.
    const stripped = content.replace(/^<!--[^\n]*-->\n+/, "").trim();
    expect(stripped.length, "RULES.md has no body after the banner").toBeGreaterThan(0);
  });
});
