import { join, dirname, resolve, relative, basename } from "node:path";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import type { SoftwareTeamsStorage } from "../storage/interface";
import { getComponent } from "../components/resolve";

/**
 * Conflict-resolution policy for files convert-agents writes:
 *
 * - `"overwrite"` — always replace existing files (sync-agents semantics).
 * - `"skip"` — never replace existing files.
 * - `"error"` — fail loudly when an existing file is encountered.
 * - `"preserve-user-owned"` — overwrite ONLY when the existing file carries
 *   the AUTO-GENERATED banner (Software Teams owns it). Files without the
 *   banner are treated as user-authored and skipped, so a fresh `init`
 *   never clobbers a hand-crafted .claude/AGENTS.md, RULES.md, or
 *   .claude/agents/* file.
 */
export type ConflictMode =
  | "overwrite"
  | "skip"
  | "error"
  | "preserve-user-owned";

/**
 * Banner prefix the writers prepend to every Software Teams-generated
 * artefact (per-agent .md, AGENTS.md catalogue, RULES.md). Used by the
 * `preserve-user-owned` conflict mode to detect which files Software
 * Teams owns vs. which the user authored.
 */
export const AUTO_GENERATED_PREFIX = "<!-- AUTO-GENERATED by software-teams sync-agents";

/**
 * True when the file's first non-blank line opens with the
 * AUTO_GENERATED_PREFIX banner. Existence-and-readability is the caller's
 * responsibility.
 */
function hasAutoGeneratedBanner(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf-8");
    const firstNonBlank =
      content.split("\n").find((l: string) => l.trim().length > 0) ?? "";
    return firstNonBlank.trim().startsWith(AUTO_GENERATED_PREFIX);
  } catch {
    return false;
  }
}

/**
 * Resolves how to handle an existing target file under each conflict mode.
 * Returns `true` when the writer should proceed (write/overwrite); the
 * writer is also responsible for pushing onto `result.skipped` or
 * `result.errors` when it decides not to proceed.
 */
function shouldWriteUnderConflict(
  outPath: string,
  mode: ConflictMode,
  result: ConvertAgentsResult,
): boolean {
  if (!existsSync(outPath)) return true;
  if (mode === "overwrite") return true;
  if (mode === "skip") {
    result.skipped.push(outPath);
    return false;
  }
  if (mode === "error") {
    result.errors.push({
      file: outPath,
      reason: "target file already exists and onConflict='error'",
    });
    return false;
  }
  // preserve-user-owned: overwrite only when we recognise our own banner.
  if (hasAutoGeneratedBanner(outPath)) return true;
  result.skipped.push(outPath);
  return false;
}

export interface ConvertAgentsOptions {
  /**
   * Source directory containing canonical `software-teams-*.md` agent specs.
   * Defaults to `.software-teams/framework/agents` if it exists, else `agents/` at repo root.
   */
  sourceDir?: string;
  /**
   * Target directory for the generated Claude-Code-native subagent files.
   * Defaults to `.claude/agents`.
   */
  targetDir?: string;
  /**
   * Working directory used to resolve default source/target paths.
   * Defaults to `process.cwd()`.
   */
  cwd?: string;
  /** When true, no files are written. */
  dryRun?: boolean;
  /** Behaviour when the target file already exists. Default `overwrite`. */
  onConflict?: ConflictMode;
  /** Optional storage adapter (currently informational; fs is used by default). */
  storage?: SoftwareTeamsStorage;
}

export interface ConvertAgentsResult {
  written: string[];
  skipped: string[];
  errors: { file: string; reason: string }[];
}

export interface AgentFrontmatter {
  name: string;
  description: string;
  model: string;
  tools: string[];
  // Software Teams-only fields (preserved on input, dropped on output)
  category?: string;
  team?: string;
  requires_components?: string[];
  [key: string]: unknown;
}

const REQUIRED_FIELDS: readonly string[] = [
  "name",
  "description",
  "model",
  "tools",
];

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/;

interface ParsedAgentFile {
  frontmatter: Record<string, unknown>;
  body: string;
}

/**
 * Parse YAML frontmatter and body from a markdown source string.
 * Throws when the file does not start with a frontmatter block.
 */
function parseAgentFile(content: string, filePath: string): ParsedAgentFile {
  const match = content.match(FRONTMATTER_RE);
  if (!match) {
    throw new Error(
      `convert-agents: ${filePath} is missing YAML frontmatter (expected leading '---' block)`,
    );
  }
  let frontmatter: Record<string, unknown>;
  try {
    frontmatter = (parseYaml(match[1]) ?? {}) as Record<string, unknown>;
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    throw new Error(`convert-agents: failed to parse frontmatter in ${filePath}: ${reason}`);
  }
  return { frontmatter, body: match[2] ?? "" };
}

/**
 * Validate that the parsed frontmatter contains every Claude-Code-required field.
 * Throws an Error listing all missing or malformed fields with the file path.
 */
export function validateAgentFrontmatter(
  frontmatter: Record<string, unknown>,
  filePath: string,
): asserts frontmatter is AgentFrontmatter {
  const missing: string[] = [];

  for (const field of REQUIRED_FIELDS) {
    const value = frontmatter[field];
    if (value === undefined || value === null) {
      missing.push(field);
      continue;
    }
    if (field === "tools") {
      if (!Array.isArray(value) || value.length === 0) {
        missing.push("tools (must be a non-empty array)");
      } else if (!value.every((t) => typeof t === "string")) {
        missing.push("tools (all entries must be strings)");
      }
    } else if (typeof value !== "string" || value.trim() === "") {
      missing.push(`${field} (must be a non-empty string)`);
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `convert-agents: ${filePath} is missing required frontmatter field(s): ${missing.join(", ")}`,
    );
  }
}

/**
 * Build the deterministic output frontmatter object containing only the
 * fields Claude Code subagents understand: name, description, model, tools.
 */
function buildOutputFrontmatter(fm: AgentFrontmatter): {
  name: string;
  description: string;
  model: string;
  tools: string[];
} {
  return {
    name: fm.name,
    description: fm.description,
    model: fm.model,
    tools: [...fm.tools].sort((a, b) => a.localeCompare(b)),
  };
}

// ---------------------------------------------------------------------------
// @ST: tag expansion (sync-time inlining, design-doc §"Tag syntax in source files")
// ---------------------------------------------------------------------------

/** Verbatim regex from the design doc. */
const ST_TAG_RE = /@ST:([A-Za-z][A-Za-z0-9-]*)(?::([A-Za-z][A-Za-z0-9-]*))?/g;

/**
 * Replace every `@ST:Name(:Section)?` tag in `body` with the resolved
 * component text. Throws with a clear context message for any unresolved tag.
 * Pre-T11: no `@ST:` tags exist in the corpus, so this is a no-op.
 */
function expandComponentTags(body: string): string {
  return body.replace(ST_TAG_RE, (_match, name, section) => {
    try {
      return getComponent(name, section);
    } catch (err) {
      throw new Error(
        `convert-agents: unresolved component tag '@ST:${name}${section ? `:${section}` : ""}': ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  });
}

/**
 * Render a single agent source file to its Claude-Code-native form.
 * The result is byte-stable for a given input.
 */
function renderAgentOutput(parsed: ParsedAgentFile, sourcePath: string): string {
  const fm = parsed.frontmatter as AgentFrontmatter;
  const outFm = buildOutputFrontmatter(fm);

  const yamlBody = stringifyYaml(outFm, { lineWidth: 0 }).trimEnd();
  const banner = `<!-- AUTO-GENERATED by software-teams sync-agents — edit agents/${fm.name}.md and re-run -->`;
  const footer = `Software Teams source: ${sourcePath}`;

  // Preserve the canonical body exactly; just trim leading/trailing whitespace
  // so the banner and footer sit cleanly around it.
  // Then expand any @ST:Name(:Section)? tags synchronously.
  const body = expandComponentTags(
    parsed.body.replace(/^\s+/, "").replace(/\s+$/, ""),
  );

  return [
    "---",
    yamlBody,
    "---",
    "",
    banner,
    "",
    body,
    "",
    footer,
    "",
  ].join("\n");
}

/**
 * Resolve a possibly-relative path against `cwd`. Absolute paths are kept as-is.
 */
function resolveAgainst(cwd: string, p: string): string {
  return resolve(cwd, p);
}

/**
 * Resolve the default source directory for agent specs.
 *
 * Resolution order (post Phase B):
 * 1. `<cwd>/agents/` — self-host invocation in the Software Teams repo.
 * 2. `<cwd>/.software-teams/framework/agents/` — legacy consumer mirror
 *    (kept as a fallback for projects that initialised before Phase B).
 * 3. `<package>/agents/` — the npm-installed package's plugin-tree source
 *    (resolved relative to import.meta.dir).
 */
function resolveDefaultSourceDir(cwd: string): string {
  const selfHost = join(cwd, "agents");
  if (existsSync(selfHost)) return selfHost;
  const legacyMirror = join(cwd, ".software-teams", "framework", "agents");
  if (existsSync(legacyMirror)) return legacyMirror;
  // Package root resolution mirrors copy-framework.ts.
  const oneUp = join(import.meta.dir, "..");
  const twoUp = join(import.meta.dir, "..", "..");
  const packageRoot = existsSync(join(oneUp, "package.json")) ? oneUp : twoUp;
  return join(packageRoot, "agents");
}

/**
 * Resolve the canonical RULES.md template path. Resolution order mirrors
 * resolveDefaultSourceDir: self-host (cwd/templates), legacy consumer mirror
 * (`.software-teams/framework/templates/`), then the package root.
 */
function resolveDefaultRulesSource(cwd: string): string {
  const selfHost = join(cwd, "templates", "RULES.md");
  if (existsSync(selfHost)) return selfHost;
  const legacyMirror = join(cwd, ".software-teams", "framework", "templates", "RULES.md");
  if (existsSync(legacyMirror)) return legacyMirror;
  const oneUp = join(import.meta.dir, "..");
  const twoUp = join(import.meta.dir, "..", "..");
  const packageRoot = existsSync(join(oneUp, "package.json")) ? oneUp : twoUp;
  return join(packageRoot, "templates", "RULES.md");
}

const CATALOGUE_BANNER =
  "<!-- AUTO-GENERATED by software-teams sync-agents — edit agents/*.md and templates/AGENTS.md.template (if used) and re-run -->";
const RULES_BANNER =
  "<!-- AUTO-GENERATED by software-teams sync-agents — edit templates/RULES.md and re-run -->";

const CATALOGUE_PREAMBLE =
  "These agents are spawned via `Task subagent_type=<name>`. Each agent's full spec is in `.claude/agents/<name>.md` (auto-generated from `agents/<name>.md`). See `RULES.md` for orchestration doctrine.";

interface CatalogueEntry {
  name: string;
  model: string;
  description: string;
}

/**
 * Render the AGENTS.md catalogue table from the agents that were successfully
 * converted. Output is byte-stable for a given input set.
 */
function renderCatalogue(entries: CatalogueEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const rows = sorted.map(
    (e) => `| ${e.name} | ${e.model} | ${escapeTableCell(e.description)} |`,
  );
  return [
    CATALOGUE_BANNER,
    "",
    "# Software Teams Agent Catalogue",
    "",
    CATALOGUE_PREAMBLE,
    "",
    "| Name | Model | Description |",
    "| ---- | ----- | ----------- |",
    ...rows,
    "",
  ].join("\n");
}

/**
 * Escape characters that would break a markdown table cell (pipes, newlines).
 */
function escapeTableCell(value: string): string {
  return value.replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

/**
 * Write the agent catalogue (`AGENTS.md`) into `targetRoot`. Returns the
 * absolute path of the written file, or null if nothing was written
 * (dryRun, or skip-on-conflict).
 */
async function writeCatalogue(
  entries: CatalogueEntry[],
  targetRoot: string,
  onConflict: ConflictMode,
  dryRun: boolean,
  result: ConvertAgentsResult,
): Promise<void> {
  const outPath = join(targetRoot, "AGENTS.md");
  const rendered = renderCatalogue(entries);

  if (!shouldWriteUnderConflict(outPath, onConflict, result)) return;

  if (!dryRun) {
    if (!existsSync(targetRoot)) mkdirSync(targetRoot, { recursive: true });
    await Bun.write(outPath, rendered);
  }
  result.written.push(outPath);
}

/**
 * Copy the canonical RULES.md template into `targetRoot/RULES.md`, prepending
 * the AUTO-GENERATED banner. Idempotent.
 */
async function writeRules(
  targetRoot: string,
  sourceRulesPath: string,
  onConflict: ConflictMode,
  dryRun: boolean,
  result: ConvertAgentsResult,
): Promise<void> {
  const outPath = join(targetRoot, "RULES.md");

  if (!existsSync(sourceRulesPath)) {
    result.errors.push({
      file: sourceRulesPath,
      reason: `RULES.md template not found: ${sourceRulesPath}`,
    });
    return;
  }

  const sourceContent = await Bun.file(sourceRulesPath).text();
  const trimmed = sourceContent.replace(/^\s+/, "").replace(/\s+$/, "");
  const rendered = `${RULES_BANNER}\n\n${trimmed}\n`;

  if (!shouldWriteUnderConflict(outPath, onConflict, result)) return;

  if (!dryRun) {
    if (!existsSync(targetRoot)) mkdirSync(targetRoot, { recursive: true });
    await Bun.write(outPath, rendered);
  }
  result.written.push(outPath);
}

/**
 * Convert every canonical `software-teams-*.md` spec under `sourceDir` to a
 * Claude-Code-native subagent file under `targetDir`.
 *
 * Idempotent — invoking twice with identical inputs produces byte-identical
 * outputs. The single intended writer to `.claude/agents/`.
 */
export async function convertAgents(
  opts: ConvertAgentsOptions = {},
): Promise<ConvertAgentsResult> {
  const cwd = opts.cwd ?? process.cwd();
  const sourceDir = resolve(opts.sourceDir ? resolveAgainst(cwd, opts.sourceDir) : resolveDefaultSourceDir(cwd));
  const targetDir = resolve(opts.targetDir ? resolveAgainst(cwd, opts.targetDir) : join(cwd, ".claude", "agents"));
  const onConflict: ConflictMode = opts.onConflict ?? "overwrite";
  const dryRun = opts.dryRun === true;

  const result: ConvertAgentsResult = { written: [], skipped: [], errors: [] };

  if (!existsSync(sourceDir)) {
    result.errors.push({
      file: sourceDir,
      reason: `source directory not found: ${sourceDir}`,
    });
    return result;
  }

  const glob = new Bun.Glob("software-teams-*.md");
  const sourceFiles: string[] = [];
  for await (const file of glob.scan({ cwd: sourceDir })) {
    sourceFiles.push(file);
  }
  // Deterministic ordering for stable logs.
  sourceFiles.sort();

  if (!dryRun && !existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  const catalogueEntries: CatalogueEntry[] = [];

  for (const file of sourceFiles) {
    const sourcePath = join(sourceDir, file);
    try {
      const content = await Bun.file(sourcePath).text();
      const parsed = parseAgentFile(content, sourcePath);
      validateAgentFrontmatter(parsed.frontmatter, sourcePath);

      const fm = parsed.frontmatter as AgentFrontmatter;
      const outName = `${fm.name}.md`;
      const outPath = join(targetDir, outName);

      // Use the relative-from-cwd source path in the footer so output is
      // portable across machines and idempotent.
      const relSource = relative(cwd, sourcePath) || basename(sourcePath);
      const rendered = renderAgentOutput(parsed, relSource);

      if (!shouldWriteUnderConflict(outPath, onConflict, result)) {
        // Still include in the catalogue — the file represents a
        // registered agent even when this run skipped writing it.
        catalogueEntries.push({
          name: fm.name,
          model: fm.model,
          description: fm.description,
        });
        continue;
      }

      if (!dryRun) {
        const dir = dirname(outPath);
        if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
        await Bun.write(outPath, rendered);
      }
      result.written.push(outPath);
      catalogueEntries.push({
        name: fm.name,
        model: fm.model,
        description: fm.description,
      });
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      result.errors.push({ file: sourcePath, reason });
    }
  }

  // Emit the catalogue and rules document alongside the per-agent files.
  // `targetRoot` defaults to the parent of `targetDir` (i.e. `.claude/`).
  const targetRoot = dirname(targetDir);
  const rulesSource = resolveDefaultRulesSource(cwd);

  if (catalogueEntries.length > 0) {
    await writeCatalogue(catalogueEntries, targetRoot, onConflict, dryRun, result);
  }
  await writeRules(targetRoot, rulesSource, onConflict, dryRun, result);

  return result;
}
