import type { OrchestrationTask, ParsedOrchestration } from "./parse-orchestration";

// ---------------------------------------------------------------------------
// Orchestration plan → Claude Code Workflow script compiler.
//
// Software Teams already produces a wave-based task graph (Tier 2 of the
// three-tier plan). The same graph maps directly onto a Claude Code `Workflow`
// script: each wave is a barrier (`await parallel([...])`), each task is an
// `agent()` call pinned to its specialist via `agentType` and forced to return
// a structured result via `schema`. Running it through the Workflow tool means
// the wave gates are GUARANTEED by code (not the orchestrator LLM remembering
// to wait), the per-spawn prompts stay tight, and every specialist returns a
// validated envelope — deterministic, token-lean orchestration.
//
// This module is pure (data → string) so it is unit-testable; the
// `compile-workflow` command handles file IO.
// ---------------------------------------------------------------------------

export interface CompileWorkflowOptions {
  /** Append a final QA-tester verification phase. Default true. */
  qa?: boolean;
}

/** Escape a string for safe embedding inside a generated template literal. */
function escTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/** Emit a string as a JS double-quoted literal (safe for identifiers/labels). */
function lit(s: string): string {
  return JSON.stringify(s);
}

/** Group tasks by wave number, ascending. */
export function groupByWave(tasks: OrchestrationTask[]): Array<[number, OrchestrationTask[]]> {
  const byWave = new Map<number, OrchestrationTask[]>();
  for (const t of tasks) {
    const arr = byWave.get(t.wave) ?? [];
    arr.push(t);
    byWave.set(t.wave, arr);
  }
  return [...byWave.entries()].sort((a, b) => a[0] - b[0]);
}

/** Build a safe-ish workflow name from a slug. */
function workflowName(slug: string): string {
  const cleaned = slug.replace(/[^A-Za-z0-9_-]/g, "-").replace(/^-+|-+$/g, "");
  return `st-impl-${cleaned || "plan"}`;
}

/**
 * Compile a parsed orchestration plan into a Claude Code Workflow script.
 * Returns the script source (JavaScript, NOT TypeScript).
 *
 * Throws if the plan has no tasks — there is nothing to orchestrate.
 */
export function buildWorkflowScript(
  parsed: ParsedOrchestration,
  options: CompileWorkflowOptions = {},
): string {
  const { tasks, slug, planId, specLink } = parsed;
  if (tasks.length === 0) {
    throw new Error(
      `Orchestration plan '${slug}' has no tasks — nothing to compile into a workflow.`,
    );
  }
  const qa = options.qa !== false;

  const waves = groupByWave(tasks);
  const name = workflowName(slug);
  const specRef = specLink ?? `${slug}.spec.md`;

  // meta.phases — one per wave, plus an optional Verify phase.
  const phaseEntries = waves.map(
    ([wave, ws]) =>
      `    { title: ${lit(`Wave ${wave}`)}, detail: ${lit(
        `${ws.length} task(s): ${ws.map((t) => t.taskId).join(", ")}`,
      )} },`,
  );
  if (qa) {
    phaseEntries.push(
      `    { title: "Verify", detail: "QA-tester verifies the plan against its spec" },`,
    );
  }

  const header = `// AUTO-GENERATED by \`software-teams compile-workflow\` from
//   ${slug}.orchestration.md  (plan ${planId}, ${tasks.length} task(s), ${waves.length} wave(s))
//
// Deterministic implementation of this plan. Run it with the Claude Code
// Workflow tool (requires opt-in — e.g. mention "ultracode" or ask Claude to
// run this workflow). Wave gates are real code barriers; each task is pinned to
// its specialist and returns a validated structured result. Specialists do NOT
// commit — they report \`commits_pending\`; the orchestrator commits after the
// workflow returns, per the Software Teams quality doctrine.
//
// Regenerate after editing the orchestration plan; do not hand-edit.`;

  const meta = `export const meta = {
  name: ${lit(name)},
  description: ${lit(
    `Software Teams deterministic implementation of ${slug} — ${tasks.length} task(s) across ${waves.length} wave(s)`,
  )},
  phases: [
${phaseEntries.join("\n")}
  ],
}`;

  const schema = `// Structured envelope every specialist must return (mirrors the Software
// Teams reporting contract). Validation + retry happens at the tool layer.
const TASK_RESULT = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["complete", "blocked", "failed"] },
    summary: { type: "string", description: "One-line outcome" },
    files_modified: { type: "array", items: { type: "string" } },
    files_created: { type: "array", items: { type: "string" } },
    commits_pending: {
      type: "array",
      items: {
        type: "object",
        properties: {
          message: { type: "string" },
          files: { type: "array", items: { type: "string" } },
        },
      },
    },
    deviations: { type: "string", description: "Anything that diverged from the slice" },
  },
  required: ["status", "summary"],
}`;

  // Per-wave bodies.
  const waveBlocks = waves.map(([wave, ws]) => {
    const calls = ws
      .map((t) => {
        const prompt =
          `Implement Software Teams task ${t.taskId} — ${t.name}.\n\n` +
          `Your task slice: ${t.slice}\n` +
          `Spec (acceptance criteria & context): ${specRef}\n\n` +
          `Read the slice and the spec sections it cites, then implement the task ` +
          `following your agent specification. Do NOT run git commit/add/push — ` +
          `leave changes in the working tree and report them in commits_pending. ` +
          `Return the structured TASK_RESULT.`;
        const label = `${t.taskId} · ${t.agent}`;
        return `    () => agent(\`${escTemplate(prompt)}\`, {
      label: ${lit(label)},
      phase: ${lit(`Wave ${wave}`)},
      agentType: ${lit(t.agent)},
      schema: TASK_RESULT,
    }),`;
      })
      .join("\n");
    return `phase(${lit(`Wave ${wave}`)})
log(${lit(`Wave ${wave}: dispatching ${ws.length} task(s) — ${ws.map((t) => t.taskId).join(", ")}`)})
results.push(
  ...(
    await parallel([
${calls}
    ])
  ).filter(Boolean),
)`;
  });

  const qaBlock = qa
    ? `
phase("Verify")
const verification = await agent(
  \`${escTemplate(
    `Verify the completed implementation of ${slug} against its spec at ${specRef}. ` +
      `Run the project's full test suite and quality gates (\`software-teams verify\`). ` +
      `Confirm every acceptance criterion is met. Report pass/fail with specifics — ` +
      `do NOT fix issues yourself, report them.`,
  )}\`,
  {
    label: "qa · software-teams-qa-tester",
    phase: "Verify",
    agentType: "software-teams-qa-tester",
    schema: {
      type: "object",
      properties: {
        passed: { type: "boolean" },
        failures: { type: "array", items: { type: "string" } },
        summary: { type: "string" },
      },
      required: ["passed", "summary"],
    },
  },
)
`
    : "";

  const ret = qa
    ? `return { slug: ${lit(slug)}, tasks: results, verification }`
    : `return { slug: ${lit(slug)}, tasks: results }`;

  return `${header}

${meta}

${schema}

const results = []

${waveBlocks.join("\n\n")}
${qaBlock}
${ret}
`;
}
