// ---------------------------------------------------------------------------
// .gitignore management for `software-teams init`.
//
// `init` generates/installs a set of artefacts under `.software-teams/` and
// `.claude/`. These are regenerated by `init` / `sync-agents` per clone, so by
// default they are gitignored (they otherwise show up as dozens of untracked
// files). A consumer who wants to version-control any of them removes that line.
//
// The block is delimited by sentinels so it can be REFRESHED idempotently on
// every init (the previous implementation wrote it once and never updated it,
// so new artefacts — hooks, statusline, etc. — leaked on upgraded projects).
// A legacy single-marker block (pre-0.13) is migrated to the sentinel form.
// ---------------------------------------------------------------------------

const BLOCK_START =
  "# >>> Software Teams — generated artefacts (managed by 'software-teams init'); remove a line to version-control it >>>";
const BLOCK_END = "# <<< Software Teams <<<";
const LEGACY_MARKER = "# Software Teams framework";

/**
 * Paths `software-teams init` generates/installs. Gitignored by default.
 *
 * - `.claude/agents/software-teams-*.md` uses a prefix so a consumer's OWN
 *   custom agents under `.claude/agents/` are still tracked.
 * - `.claude/CLAUDE.md` and `.claude/settings.json` are included because `init`
 *   generates them; teams that want to share them remove the line.
 */
export const ST_GITIGNORE_PATHS: readonly string[] = [
  ".software-teams/",
  ".claude/commands/st/",
  ".claude/agents/software-teams-*.md",
  ".claude/AGENTS.md",
  ".claude/RULES.md",
  ".claude/CLAUDE.md",
  ".claude/hooks/",
  ".claude/statusline/",
  ".claude/settings.json",
  ".claude/settings.local.json",
];

/** Build the managed block (sentinels + paths). */
export function buildManagedBlock(paths: readonly string[] = ST_GITIGNORE_PATHS): string {
  return [BLOCK_START, ...paths, BLOCK_END].join("\n");
}

/** Escape a literal string for use inside a RegExp. */
function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Remove any prior managed block — the sentinel form OR the legacy single-marker form. */
function stripManagedBlock(content: string): string {
  return content
    // Sentinel-delimited block (non-greedy between the start/end markers).
    .replace(new RegExp(`${escapeRegex(BLOCK_START)}[\\s\\S]*?${escapeRegex(BLOCK_END)}`, "g"), "")
    // Legacy single-marker block: the marker line + the contiguous ST path lines after it.
    .replace(
      new RegExp(`(^|\\n)${escapeRegex(LEGACY_MARKER)}[^\\n]*(\\n(?:\\.software-teams/|\\.claude/)[^\\n]*)*`, "g"),
      "",
    );
}

/**
 * Return `existing` .gitignore content with the Software Teams managed block
 * inserted or refreshed. Idempotent: running it on its own output is a no-op.
 * All non-managed content is preserved.
 */
export function updateGitignore(existing: string, paths: readonly string[] = ST_GITIGNORE_PATHS): string {
  const base = stripManagedBlock(existing)
    .replace(/\n{3,}/g, "\n\n")
    .replace(/\s+$/, "");
  const block = buildManagedBlock(paths);
  return (base ? base + "\n\n" : "") + block + "\n";
}
