import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const RULE_CATEGORIES = [
  "general",
  "backend",
  "frontend",
  "testing",
  "devops",
] as const;

export type RuleCategory = (typeof RULE_CATEGORIES)[number];

const RULE_PATHS: Record<RuleCategory, readonly string[]> = {
  // No paths key means startup-loaded and re-injected after compaction.
  general: [],
  backend: [
    "**/*.{php,py,rb,go,java,kt,cs}",
    "**/{api,server,backend,controllers,models,services,routes,database,migrations}/**/*",
  ],
  frontend: [
    "**/*.{tsx,jsx,vue,svelte,css,scss,sass,less}",
    "**/{components,pages,views,hooks,frontend,client,ui}/**/*",
  ],
  testing: [
    "**/*.test.*",
    "**/*.spec.*",
    "**/{test,tests,__tests__}/**/*",
  ],
  devops: [
    ".github/workflows/**/*",
    "**/{Dockerfile,docker-compose.yml,docker-compose.yaml,Makefile,Taskfile.yml}",
    "**/*.{tf,hcl}",
  ],
};

const FRONTMATTER_RE = /^---\r?\n[\s\S]*?\r?\n---\r?\n?/;

export function nativeRulesDir(cwd: string): string {
  return join(cwd, ".claude", "rules");
}

export function nativeRulePath(cwd: string, category: string): string {
  return join(nativeRulesDir(cwd), `${category}.md`);
}

export function stripRuleFrontmatter(content: string): string {
  return content.replace(FRONTMATTER_RE, "").trim();
}

export function renderNativeRule(category: RuleCategory, content: string): string {
  const body = stripRuleFrontmatter(content);
  const paths = RULE_PATHS[category];
  if (paths.length === 0) return `${body}\n`;
  const renderedPaths = paths.map((path) => `  - "${path}"`).join("\n");
  return `---\npaths:\n${renderedPaths}\n---\n\n${body}\n`;
}

export function renderFallbackNativeRule(content: string): string {
  return `${stripRuleFrontmatter(content)}\n`;
}

export function hasRuleContent(content: string): boolean {
  return stripRuleFrontmatter(content).split(/\r?\n/).some((line) => {
    const trimmed = line.trim();
    return Boolean(trimmed && !trimmed.startsWith("#") && !trimmed.startsWith("<!--"));
  });
}

/**
 * Move pre-1.0 learned rules into Claude Code's native project-rule location.
 * Known framework-only procedure files are retired; unknown custom categories
 * are preserved as unconditional native rules, matching their old semantics.
 */
export interface LegacyRulesMigration {
  migrated: string[];
  warnings: string[];
}

export function migrateLegacyRules(cwd: string): LegacyRulesMigration {
  const generatedRules = join(cwd, ".claude", "RULES.md");
  const retiredGeneratedRules = existsSync(generatedRules)
    && readFileSync(generatedRules, "utf8").startsWith(
      "<!-- AUTO-GENERATED by software-teams sync-agents",
    );
  if (retiredGeneratedRules) rmSync(generatedRules, { force: true });

  const claudeMd = join(cwd, ".claude", "CLAUDE.md");
  if (existsSync(claudeMd)) {
    const current = readFileSync(claudeMd, "utf8");
    const withoutImport = retiredGeneratedRules
      ? current.replace(/^@\.claude\/RULES\.md\s*\r?\n?/m, "")
      : current;
    // The old generated section always began with this exact instruction, but
    // consumers may have reordered later headings. Stop at the next H2 or EOF.
    const withoutLegacySection = withoutImport.replace(
      /\n## Rules\n\nIMPORTANT: Always read rules BEFORE starting any work\.[\s\S]*?(?=\n## |$)/,
      "\n",
    );
    if (withoutLegacySection !== current) writeFileSync(claudeMd, withoutLegacySection);
  }

  const warnings: string[] = [];
  if (existsSync(generatedRules) && !retiredGeneratedRules) {
    warnings.push("Preserved unrecognised .claude/RULES.md; remove its obsolete imports manually if needed.");
  }
  const legacyDir = join(cwd, ".software-teams", "rules");
  const migrated: string[] = [];
  if (existsSync(legacyDir)) mkdirSync(nativeRulesDir(cwd), { recursive: true });

  for (const filename of existsSync(legacyDir)
    ? readdirSync(legacyDir).filter((file) => file.endsWith(".md"))
    : []) {
    const category = filename.replace(/\.md$/, "");
    const source = join(legacyDir, filename);
    if (category === "commits" || category === "deviations") {
      rmSync(source, { force: true });
      continue;
    }

    const content = readFileSync(source, "utf8");
    const destination = nativeRulePath(cwd, category);
    if (!existsSync(destination)) {
      const known = RULE_CATEGORIES.find((candidate) => candidate === category);
      const rendered = known
        ? renderNativeRule(known, content)
        : renderFallbackNativeRule(content);
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, rendered);
      migrated.push(filename);
    } else if (hasRuleContent(content)) {
      const current = readFileSync(destination, "utf8");
      const body = stripRuleFrontmatter(content);
      if (!current.includes(body)) {
        writeFileSync(destination, `${current.trimEnd()}\n\n${body}\n`);
        migrated.push(filename);
      }
    }
    rmSync(source, { force: true });
  }

  if (existsSync(legacyDir) && readdirSync(legacyDir).length === 0) {
    rmSync(legacyDir, { recursive: true, force: true });
  }
  if (existsSync(claudeMd)) {
    const remaining = readFileSync(claudeMd, "utf8");
    if (remaining.includes(".software-teams/rules")) {
      warnings.push(
        "CLAUDE.md still references retired .software-teams/rules; migrate that custom instruction to .claude/rules/.",
      );
    }
    if (remaining.includes("@.claude/RULES.md") && !existsSync(generatedRules)) {
      warnings.push("CLAUDE.md still imports missing .claude/RULES.md; remove the stale custom import.");
    }
  }
  return { migrated: migrated.sort(), warnings };
}
