#!/usr/bin/env bun
// scripts/rename-jdi-to-st.ts
//
// T11: Bulk-rename <JDI:Name /> → @ST:Name across the corpus.
//
// Rewrite rules (applied in this order per the task spec):
//   a. Attribute form: <JDI:Name attr="value" /> → @ST:Name:value
//      Known attrs: mode, source, scope, post — all treated as section name.
//      Unknown attr → WARN + halt (do not silently drop).
//   b. Section form: <JDI:Name:Section /> → @ST:Name:Section
//   c. Whole-component form: <JDI:Name /> → @ST:Name
//
// Special case: <JDI:Architect:Analyse />, <JDI:Architect:Design />,
// <JDI:Architect:Review /> → deleted (replaced with empty string).
//
// Backtick guard (R-3-02): inside ``` fenced blocks OR inside `inline` spans,
// do NOT rewrite UNLESS the fenced block is immediately preceded by
// <!-- migrate-tags --> on the line directly before the opening fence.
//
// Usage: bun run scripts/rename-jdi-to-st.ts [--dry-run]

import { join } from "node:path";

const DRY_RUN = process.argv.includes("--dry-run");
const ROOT = join(import.meta.dir, "..");

// Known attribute names that map directly to section names.
const KNOWN_ATTRS = new Set(["mode", "source", "scope", "post"]);

// Note: Architect sub-components ("Analyse", "Design", "Review") are DELETED
// rather than renamed; the deletion is handled inline at the rewrite site.

// Directories/patterns to include in the walk.
const INCLUDE_DIRS = [
  join(ROOT, "framework"),
  join(ROOT, ".claude", "agents"),
  join(ROOT, ".claude", "commands"),
  // Root-level agents/ directory (parallel copy generated by sync-agents or older tooling).
  join(ROOT, "agents"),
  // Installed framework copy — used by sync-agents at runtime.
  join(ROOT, ".software-teams", "framework"),
];
// Single files to include.
const INCLUDE_FILES = [
  join(ROOT, ".claude", "AGENTS.md"),
  join(ROOT, ".claude", "RULES.md"),
];
// Plan slices for the current plan only (3-01-*).
const PLANS_DIR = join(ROOT, ".software-teams", "plans");

// Note: walk uses INCLUDE_DIRS allowlist; node_modules / dist / .git are
// outside the allowlist and so already excluded.
const EXCLUDE_FILES = new Set([
  join(ROOT, "docs", "typescript-injection-design.md"),
  join(ROOT, "scripts", "grep-audit-allowlist.txt"),
  join(ROOT, "scripts", "rename-jdi-to-st.ts"),
]);

// --- File collection --------------------------------------------------------

async function collectFiles(): Promise<string[]> {
  const files: string[] = [];

  const glob = new Bun.Glob("**/*.md");

  for (const dir of INCLUDE_DIRS) {
    for await (const rel of glob.scan({ cwd: dir, onlyFiles: true })) {
      const abs = join(dir, rel);
      if (!EXCLUDE_FILES.has(abs)) {
        files.push(abs);
      }
    }
  }

  for (const f of INCLUDE_FILES) {
    if (!EXCLUDE_FILES.has(f)) {
      files.push(f);
    }
  }

  // Plan slices for current plan (3-01-*) only.
  const planGlob = new Bun.Glob("3-01-*.md");
  for await (const rel of planGlob.scan({ cwd: PLANS_DIR, onlyFiles: true })) {
    const abs = join(PLANS_DIR, rel);
    if (!EXCLUDE_FILES.has(abs)) {
      files.push(abs);
    }
  }

  // Deduplicate (INCLUDE_FILES might overlap with a glob scan).
  return [...new Set(files)];
}

// --- Rewrite logic ----------------------------------------------------------

interface RewriteResult {
  changed: boolean;
  content: string;
  replacements: number;
  warnings: string[];
}

// Returns the value-string with an `@ST:` prefix rewrite applied at all
// non-protected positions. We process line-by-line so we can track fenced
// block state.
function rewriteContent(filePath: string, original: string): RewriteResult {
  const lines = original.split("\n");
  const out: string[] = [];
  let inFence = false;
  let fenceMigratable = false; // true when <!-- migrate-tags --> preceded fence
  let totalReplacements = 0;
  const warnings: string[] = [];
  let haltOnUnknownAttr = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;

    // Detect fence boundaries.
    const isFenceLine = /^```/.test(line.trimStart());
    if (isFenceLine) {
      if (!inFence) {
        // Opening fence. Check the immediately preceding line for migrate-tags.
        const prevLine = i > 0 ? lines[i - 1]! : "";
        fenceMigratable = prevLine.trim() === "<!-- migrate-tags -->";
        inFence = true;
        out.push(line);
        continue;
      } else {
        // Closing fence.
        inFence = false;
        fenceMigratable = false;
        out.push(line);
        continue;
      }
    }

    // Inside fenced block: only rewrite if migratable.
    if (inFence && !fenceMigratable) {
      out.push(line);
      continue;
    }

    // Rewrite the line (or rewrite it if fenceMigratable inside fence).
    const { result, replacements, warning } = rewriteLine(line, filePath);
    if (warning) {
      warnings.push(warning);
      haltOnUnknownAttr = true;
    }
    totalReplacements += replacements;
    out.push(result);
  }

  if (haltOnUnknownAttr) {
    return { changed: false, content: original, replacements: 0, warnings };
  }

  const content = out.join("\n");
  return {
    changed: content !== original,
    content,
    replacements: totalReplacements,
    warnings,
  };
}

// Rewrite a single line, honouring inline-backtick protection.
function rewriteLine(
  line: string,
  filePath: string,
): { result: string; replacements: number; warning: string | null } {
  // Split the line into segments: [outside-backtick, inside-backtick, outside, ...].
  // We only rewrite "outside" segments.
  // Strategy: tokenise by backtick spans.
  const segments = splitByBackticks(line);
  let replacements = 0;
  let warning: string | null = null;
  const rebuilt: string[] = [];

  for (const seg of segments) {
    if (seg.protected) {
      rebuilt.push(seg.text);
      continue;
    }
    const { text: rewritten, count, warn } = applyRewrites(seg.text, filePath);
    replacements += count;
    if (warn && !warning) warning = warn;
    rebuilt.push(rewritten);
  }

  return { result: rebuilt.join(""), replacements, warning };
}

// Tokenise a line into protected (inside backticks) and unprotected segments.
function splitByBackticks(
  line: string,
): Array<{ text: string; protected: boolean }> {
  const result: Array<{ text: string; protected: boolean }> = [];
  // Match backtick spans: `...` or ``...``
  // Regex: (`+)([^`]*)\1 — matches the same number of opening/closing backticks.
  const backtickRe = /(`+)(.*?)\1/gs;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = backtickRe.exec(line)) !== null) {
    const [full, , ] = match;
    const start = match.index;
    if (start > lastIndex) {
      result.push({ text: line.slice(lastIndex, start), protected: false });
    }
    result.push({ text: full!, protected: true });
    lastIndex = start + full!.length;
  }

  if (lastIndex < line.length) {
    result.push({ text: line.slice(lastIndex), protected: false });
  }

  return result;
}

// Apply rewrites to an unprotected text segment. Returns modified text,
// replacement count, and optional warning (unknown attribute).
function applyRewrites(
  text: string,
  filePath: string,
): { text: string; count: number; warn: string | null } {
  let count = 0;
  let warn: string | null = null;
  let result = text;

  // --- Special case: delete Architect broken refs ---
  // <JDI:Architect:Analyse />, <JDI:Architect:Design />, <JDI:Architect:Review />
  result = result.replace(
    /<JDI:Architect:(Analyse|Design|Review)\s*\/>/g,
    (_, section) => {
      count++;
      // Insert deletion comment instead of empty string so diff is traceable.
      return `<!-- T11: removed broken Architect:${section} reference -->`;
    },
  );

  // --- Step a: Attribute form ---
  // <JDI:Name attr="value" />
  result = result.replace(
    /<JDI:([A-Z][A-Za-z0-9]*)\s+([a-z]+)="([^"\\]*)"\s*\/>/g,
    (full, name, attr, value) => {
      if (!KNOWN_ATTRS.has(attr)) {
        warn = `UNKNOWN ATTR '${attr}' in tag '${full}' at file ${filePath} — halting`;
        return full; // leave unchanged; caller will halt
      }
      count++;
      return `@ST:${name}:${value}`;
    },
  );

  // Also handle backslash-escaped quotes inside fenced code blocks that embed
  // shell-literal strings, e.g. <JDI:PRReview post=\"false\" /> — but those
  // are inside fenced blocks without migrate-tags, so they won't reach here.
  // If they somehow do reach here, handle them:
  result = result.replace(
    /<JDI:([A-Z][A-Za-z0-9]*)\s+([a-z]+)=\\"([^"\\]*)\\"\s*\/>/g,
    (full, name, attr, value) => {
      if (!KNOWN_ATTRS.has(attr)) {
        warn = `UNKNOWN ATTR '${attr}' in escaped-quote tag '${full}' at file ${filePath} — halting`;
        return full;
      }
      count++;
      return `@ST:${name}:${value}`;
    },
  );

  // --- Step b: Section form ---
  // <JDI:Name:Section />
  result = result.replace(
    /<JDI:([A-Z][A-Za-z0-9]*):([A-Za-z0-9][A-Za-z0-9-]*)\s*\/>/g,
    (_, name, section) => {
      count++;
      return `@ST:${name}:${section}`;
    },
  );

  // --- Step c: Whole-component form ---
  // <JDI:Name />
  result = result.replace(/<JDI:([A-Z][A-Za-z0-9]*)\s*\/>/g, (_, name) => {
    count++;
    return `@ST:${name}`;
  });

  return { text: result, count, warn };
}

// --- Main -------------------------------------------------------------------

async function main() {
  console.log(`rename-jdi-to-st.ts — ${DRY_RUN ? "DRY RUN" : "LIVE"}`);
  console.log(`Root: ${ROOT}\n`);

  const files = await collectFiles();
  console.log(`Files to scan: ${files.length}`);

  let totalFiles = 0;
  let totalReplacements = 0;
  let haltRequested = false;

  for (const filePath of files.sort()) {
    const file = Bun.file(filePath);
    const original = await file.text();

    if (!original.includes("<JDI:")) continue;

    const { changed, content, replacements, warnings } = rewriteContent(
      filePath,
      original,
    );

    if (warnings.length > 0) {
      for (const w of warnings) {
        console.error(`[WARN] ${w}`);
      }
      haltRequested = true;
    }

    if (haltRequested) break;

    if (changed) {
      totalFiles++;
      totalReplacements += replacements;
      const rel = filePath.slice(ROOT.length + 1);
      console.log(`  [${replacements} subs] ${rel}`);

      if (!DRY_RUN) {
        await Bun.write(filePath, content);
      }
    }
  }

  if (haltRequested) {
    console.error("\n[HALT] Unknown attribute encountered — no files written.");
    process.exit(1);
  }

  console.log(
    `\nDone. ${totalFiles} files modified, ${totalReplacements} substitutions.`,
  );
  if (DRY_RUN) {
    console.log("(dry-run: no files written)");
  }
}

await main();
