import { afterEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  migrateLegacyRules,
  nativeRulePath,
  renderNativeRule,
  stripRuleFrontmatter,
} from "../native-rules";

const dirs: string[] = [];
function fixture(): string {
  const dir = mkdtempSync(join(tmpdir(), "st-rules-"));
  dirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

describe("native project rules", () => {
  test("renders category-specific paths and leaves general rules unconditional", () => {
    const backend = renderNativeRule("backend", "# Backend\n- Use DTOs\n");
    expect(backend).toContain('"**/*.{php,py,rb,go,java,kt,cs}"');
    expect(backend).toContain("Use DTOs");
    expect(stripRuleFrontmatter(backend)).toBe("# Backend\n- Use DTOs");

    const general = renderNativeRule("general", "# General\n- Never guess\n");
    expect(general).not.toContain("paths:");
    expect(general).toBe("# General\n- Never guess\n");
  });

  test("migrates learned legacy rules and retires generated RULES.md wiring", () => {
    const cwd = fixture();
    mkdirSync(join(cwd, ".claude"), { recursive: true });
    writeFileSync(
      join(cwd, ".claude", "RULES.md"),
      "<!-- AUTO-GENERATED by software-teams sync-agents — edit templates/RULES.md and re-run -->\n# Old doctrine\n",
    );
    writeFileSync(
      join(cwd, ".claude", "CLAUDE.md"),
      "# Project\n@.claude/AGENTS.md\n@.claude/RULES.md\n\n## Rules\n\nIMPORTANT: Always read rules BEFORE starting any work.\nlegacy\n\n## Scope Discipline\nKeep scope.\n",
    );
    const legacy = join(cwd, ".software-teams", "rules");
    mkdirSync(legacy, { recursive: true });
    writeFileSync(join(legacy, "frontend.md"), "# Frontend\n- Use design tokens\n");
    writeFileSync(join(legacy, "game-ai.md"), "# Game AI\n- Seed simulations\n");
    writeFileSync(join(legacy, "commits.md"), "# obsolete\n");
    writeFileSync(join(legacy, "deviations.md"), "# obsolete\n");

    expect(migrateLegacyRules(cwd)).toEqual({
      migrated: ["frontend.md", "game-ai.md"],
      warnings: [],
    });
    const frontend = readFileSync(nativeRulePath(cwd, "frontend"), "utf8");
    expect(frontend).toContain("Use design tokens");
    expect(frontend).toContain("**/*.{tsx,jsx,vue,svelte,css,scss,sass,less}");
    expect(readFileSync(nativeRulePath(cwd, "game-ai"), "utf8")).not.toContain("paths:");
    expect(existsSync(join(cwd, ".software-teams", "rules"))).toBe(false);
    expect(existsSync(join(cwd, ".claude", "RULES.md"))).toBe(false);
    const claudeMd = readFileSync(join(cwd, ".claude", "CLAUDE.md"), "utf8");
    expect(claudeMd).not.toContain("@.claude/RULES.md");
    expect(claudeMd).not.toContain("IMPORTANT: Always read rules");
    expect(claudeMd).toContain("## Scope Discipline");
  });

  test("preserves an existing native team rule and appends legacy learnings once", () => {
    const cwd = fixture();
    const native = nativeRulePath(cwd, "general");
    mkdirSync(join(cwd, ".claude", "rules"), { recursive: true });
    writeFileSync(native, renderNativeRule("general", "# General\n- Existing convention\n"));
    const legacy = join(cwd, ".software-teams", "rules");
    mkdirSync(legacy, { recursive: true });
    writeFileSync(join(legacy, "general.md"), "# General\n- Learned convention\n");

    migrateLegacyRules(cwd);
    migrateLegacyRules(cwd);
    const content = readFileSync(native, "utf8");
    expect(content).toContain("Existing convention");
    expect(content).toContain("Learned convention");
    expect(content.match(/Learned convention/g)).toHaveLength(1);
  });

  test("warns when a customised CLAUDE.md still references the retired rule tree", () => {
    const cwd = fixture();
    mkdirSync(join(cwd, ".claude"), { recursive: true });
    writeFileSync(
      join(cwd, ".claude", "CLAUDE.md"),
      "# Custom\nRead .software-teams/rules/security.md before audits.\n",
    );
    mkdirSync(join(cwd, ".software-teams", "rules"), { recursive: true });
    writeFileSync(join(cwd, ".software-teams", "rules", "security.md"), "# Security\n- Audit auth\n");

    const result = migrateLegacyRules(cwd);
    expect(result.migrated).toEqual(["security.md"]);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain("still references retired");

    const second = migrateLegacyRules(cwd);
    expect(second.warnings[0]).toContain("still references retired");
  });
});
