import { describe, test, expect } from "bun:test";
import { join } from "path";
import { readdirSync, readFileSync } from "fs";

const REPO_ROOT = join(import.meta.dir, "..");
const AGENTS_DIR = join(REPO_ROOT, "agents");
const COMMANDS_DIR = join(REPO_ROOT, "commands");

/**
 * Helper: recursively list all files in a directory
 */
function listFilesRecursive(dir: string): string[] {
  const files: string[] = [];
  try {
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        files.push(...listFilesRecursive(fullPath));
      } else {
        files.push(fullPath);
      }
    }
  } catch {
    // Directory may not exist yet; return empty list
  }
  return files;
}

/**
 * Helper: check if a file contains the AUTO-GENERATED banner
 */
function hasAutogeneratedBanner(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf-8");
    return /<!-- AUTO-GENERATED/.test(content);
  } catch {
    return false;
  }
}

describe("plugin content tree", () => {
  describe("agents/ directory", () => {
    test("agents/ directory exists at repo root", () => {
      const files = listFilesRecursive(AGENTS_DIR);
      expect(files.length).toBeGreaterThan(0);
    });

    test("agents/ contains at least 24 files named software-teams-*.md", () => {
      const files = listFilesRecursive(AGENTS_DIR);
      const agentFiles = files.filter((f) => f.endsWith(".md") && f.includes("software-teams-"));
      expect(agentFiles.length).toBeGreaterThanOrEqual(24);
    });

    test("every agent file has the AUTO-GENERATED banner", () => {
      const files = listFilesRecursive(AGENTS_DIR);
      const agentFiles = files.filter((f) => f.endsWith(".md"));

      for (const file of agentFiles) {
        const hasMarker = hasAutogeneratedBanner(file);
        if (!hasMarker) {
          console.error(`Missing AUTO-GENERATED banner in: ${file}`);
        }
        expect(hasMarker).toBe(true);
      }
    });

    test("agent files use software-teams- naming convention", () => {
      const files = listFilesRecursive(AGENTS_DIR);
      const agentFiles = files.filter((f) => f.endsWith(".md"));

      for (const file of agentFiles) {
        const fileName = file.split("/").pop() || "";
        expect(fileName).toMatch(/^software-teams-/);
      }
    });
  });

  describe("commands/ directory", () => {
    test("commands/ directory exists at repo root", () => {
      const files = listFilesRecursive(COMMANDS_DIR);
      expect(files.length).toBeGreaterThan(0);
    });

    test("commands/ contains at least 12 files", () => {
      const files = listFilesRecursive(COMMANDS_DIR);
      const mdFiles = files.filter((f) => f.endsWith(".md"));
      expect(mdFiles.length).toBeGreaterThanOrEqual(12);
    });

    test("every command file has the AUTO-GENERATED banner", () => {
      const files = listFilesRecursive(COMMANDS_DIR);
      const cmdFiles = files.filter((f) => f.endsWith(".md"));

      for (const file of cmdFiles) {
        const hasMarker = hasAutogeneratedBanner(file);
        if (!hasMarker) {
          console.error(`Missing AUTO-GENERATED banner in: ${file}`);
        }
        expect(hasMarker).toBe(true);
      }
    });

    test("command files are valid markdown", () => {
      const files = listFilesRecursive(COMMANDS_DIR);
      const cmdFiles = files.filter((f) => f.endsWith(".md"));

      for (const file of cmdFiles) {
        const content = readFileSync(file, "utf-8");
        expect(content.length).toBeGreaterThan(0);
        // Basic check: should have YAML frontmatter or content
        expect(content).not.toEqual("");
      }
    });
  });

  describe("combined structure", () => {
    test("agents/ and commands/ combined have expected content count", () => {
      const agentFiles = listFilesRecursive(AGENTS_DIR).filter((f) => f.endsWith(".md"));
      const cmdFiles = listFilesRecursive(COMMANDS_DIR).filter((f) => f.endsWith(".md"));

      expect(agentFiles.length).toBeGreaterThanOrEqual(24);
      expect(cmdFiles.length).toBeGreaterThanOrEqual(12);
      // Total should be at least 36 files
      expect(agentFiles.length + cmdFiles.length).toBeGreaterThanOrEqual(36);
    });

    test("all AUTO-GENERATED banners are consistent (plain text)", () => {
      const allFiles = [
        ...listFilesRecursive(AGENTS_DIR),
        ...listFilesRecursive(COMMANDS_DIR),
      ].filter((f) => f.endsWith(".md"));

      const uniqueBanners = new Set<string>();
      let fileCount = 0;
      for (const file of allFiles) {
        fileCount++;
        const content = readFileSync(file, "utf-8");
        // Match HTML comments containing AUTO-GENERATED, allowing any character until -->
        const match = content.match(/<!-- AUTO-GENERATED.*?-->/s);
        if (match) {
          uniqueBanners.add(match[0]);
        }
      }

      // All AUTO-GENERATED banners should exist and follow the pattern
      // Just verify they all exist and follow the pattern
      expect(fileCount).toBeGreaterThan(0);
      expect(uniqueBanners.size).toBeGreaterThan(0);
      for (const banner of uniqueBanners) {
        expect(banner).toMatch(/<!-- AUTO-GENERATED/);
        expect(banner).toMatch(/-->/);
      }
    });
  });
});
