import {
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeConnectionTypes,
  NodeOperationError,
} from 'n8n-workflow';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { NodeEnvelope } from '@websitelabs/software-teams';
import { toDataObject, fromDataObject } from '../../src/n8n-cast';
import { cloneRepo } from '../../src/repo/git';
import { validateOwnerRepo, validateBranchName, validateCloneUrl } from '../../src/repo/validate';
import { applyAndResolve, pushBranch } from '../../src/repo/merge';
import type { RepoContext } from '../../src/repo/repo-context';

type RunAgentTurnFn = (
  input: NodeEnvelope,
  repoContext?: RepoContext,
  githubToken?: string,
) => Promise<NodeEnvelope>;

type EnumerateAgentResultsFn = (state: import('../../src/orchestration/run-state/shapes').RunState) => import('../../src/orchestration/run-state/transitions').AgentResult[];
type ReadRunStateFn = (staticData: Record<string, unknown>, correlationId: string) => import('../../src/orchestration/run-state/shapes').RunState | null;

const SINGLE_TURN_MODULE = '../../src/execution/single-turn';
const RUN_STATE_MODULE = '../../src/orchestration/run-state/transitions';
const GLOBAL_STORE_MODULE = '../../src/orchestration/run-state/global-store';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { runAgentTurn } = require(SINGLE_TURN_MODULE) as { runAgentTurn: RunAgentTurnFn };
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { enumerateAgentResults } = require(RUN_STATE_MODULE) as { enumerateAgentResults: EnumerateAgentResultsFn };
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { readRunState } = require(GLOBAL_STORE_MODULE) as { readRunState: ReadRunStateFn };

function buildFeatureBranchName(correlationId: string): string {
  return `feat/st-run-${correlationId.slice(0, 8)}`;
}

function buildBranchUrl(ownerRepo: string, branchName: string): string {
  return `https://github.com/${ownerRepo}/tree/${branchName}`;
}

function buildRunSummary(opts: {
  readonly agentResults: import('../../src/orchestration/run-state/transitions').AgentResult[];
  readonly branchName: string;
  readonly ownerRepo: string;
  readonly correlationId: string;
}): string {
  const { agentResults, branchName, ownerRepo, correlationId } = opts;
  const lines: string[] = [
    `## Software Teams Run Summary`,
    ``,
    `**Correlation ID:** \`${correlationId}\``,
    `**Branch:** \`${branchName}\``,
    `**Repo:** \`${ownerRepo}\``,
    ``,
    `### Agent Results`,
    ``,
  ];

  for (const r of agentResults) {
    const icon = r.status === 'done' ? '[ok]' : `[${r.status}]`;
    const patch = r.changeRef ? ' (changes captured)' : ' (no changes)';
    lines.push(`- **${r.agent}** (${r.taskId}): ${icon}${patch}`);
  }

  const failedAgents = agentResults.filter((r) => r.status === 'error');
  if (failedAgents.length > 0) {
    lines.push(``, `### Failed Agents`, ``);
    for (const r of failedAgents) {
      lines.push(`- \`${r.agent}\` (${r.taskId}) — check node logs for details`);
    }
  }

  lines.push(
    ``,
    `---`,
    `*Generated by [@websitelabs/n8n-nodes-software-teams](https://github.com/websitelabs/software-teams/tree/main/packages/n8n)*`,
  );

  return lines.join('\n');
}

export class SoftwareTeamsFinaliser implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Software Teams Finaliser',
    name: 'softwareTeamsFinaliser',
    icon: 'file:softwareTeamsFinaliser.svg',
    group: ['output'],
    version: 1,
    description:
      'Terminal node for Software Teams repo-execution workflows (ADR-002). ' +
      'Reads aggregated run-state, merges all agent changes with bounded conflict ' +
      'resolution (≤3 resolver turns), pushes a feature branch, emits a branch ' +
      'artifact, and synthesises a run summary.',
    subtitle: '={{ $parameter["ownerRepo"] }}',
    defaults: { name: 'Software Teams Finaliser' },
    inputs: [NodeConnectionTypes.Main],
    outputs: [NodeConnectionTypes.Main],
    credentials: [
      { name: 'softwareTeamsApi', required: true },
    ],
    properties: [
      {
        displayName: 'Target Repository',
        name: 'ownerRepo',
        type: 'string',
        default: '',
        required: true,
        placeholder: 'owner/repo',
        description:
          'GitHub repository in owner/repo format. Must match the repository ' +
          'the Workspace node checked out.',
      },
      {
        displayName: 'Base Branch',
        name: 'baseBranch',
        type: 'string',
        default: 'main',
        required: true,
        description: 'The branch agents forked from. The feature branch merges into this.',
      },
      {
        displayName: 'Clone URL',
        name: 'cloneUrl',
        type: 'string',
        default: '',
        description:
          'Optional clone URL override. Defaults to the GitHub https URL derived from ' +
          '"owner/repo". Useful for non-GitHub hosts or SSH.',
      },
    ],
    usableAsTool: true,
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const items = this.getInputData();
    const returnData: INodeExecutionData[] = [];

    const credentials = await this.getCredentials('softwareTeamsApi');
    process.env['ANTHROPIC_API_KEY'] = credentials.anthropicApiKey as string;
    const githubToken = (credentials.githubToken as string | undefined) || undefined;

    if (!githubToken) {
      throw new NodeOperationError(
        this.getNode(),
        'No GitHub token found in the Software Teams API credential. ' +
          'Set "GitHub Token" to a personal access token with repo + PR write scopes.',
      );
    }

    const itemCount = items.length > 0 ? items.length : 1;

    for (const [i] of Array.from({ length: itemCount }).entries()) {
      try {
        const ownerRepo = validateOwnerRepo(
          (this.getNodeParameter('ownerRepo', i) as string).trim(),
        );
        const baseBranch = validateBranchName(
          (this.getNodeParameter('baseBranch', i, 'main') as string).trim() || 'main',
        );
        const cloneUrlParam = ((this.getNodeParameter('cloneUrl', i, '') as string) || '').trim();
        const cloneUrl = cloneUrlParam
          ? validateCloneUrl(cloneUrlParam)
          : `https://github.com/${ownerRepo}.git`;

        const upstream = (items[i]?.json ?? {}) as Record<string, unknown>;
        const envelope = fromDataObject<NodeEnvelope>(upstream as import('n8n-workflow').IDataObject);

        if (!envelope || typeof envelope.correlationId !== 'string') {
          throw new NodeOperationError(
            this.getNode(),
            'Incoming item is not a valid NodeEnvelope (missing correlationId). ' +
              'Wire this node after Software Teams Agent nodes.',
            { itemIndex: i },
          );
        }

        const correlationId = envelope.correlationId;

        const staticData = this.getWorkflowStaticData('global') as Record<string, unknown>;
        const runState = readRunState(staticData, correlationId);

        if (!runState) {
          throw new NodeOperationError(
            this.getNode(),
            `No aggregated run-state found for correlationId "${correlationId}". ` +
              'The plan Orchestrator must seed the run and at least one Agent must ' +
              'have run before the Finaliser can merge changes.',
            { itemIndex: i },
          );
        }

        const agentResults = enumerateAgentResults(runState);
        const changeRefs = agentResults
          .filter((r) => r.changeRef !== undefined)
          .map((r) => r.changeRef!);

        const repoDir = join(tmpdir(), 'st-finaliser', correlationId);
        const authenticatedCloneUrl = githubToken && cloneUrl.startsWith('https://')
          ? cloneUrl.replace('https://', `https://x-access-token:${githubToken}@`)
          : cloneUrl;

        await cloneRepo({ cloneUrl: authenticatedCloneUrl, branch: baseBranch, destDir: repoDir });

        const branchName = buildFeatureBranchName(correlationId);

        const mergeResult = await applyAndResolve({
          repoDir,
          branchName,
          baseBranch,
          changeRefs,
          resolver: async (conflictingFiles) => {
            const repoContext: RepoContext = {
              cloneUrl,
              ownerRepo,
              baseBranch,
              correlationId,
              worktreePath: repoDir,
            };

            const conflictPrompt =
              `You are a conflict resolver. The following files have git conflict markers:\n` +
              conflictingFiles.map((f) => `- ${f}`).join('\n') +
              `\n\nResolve all conflict markers in these files to produce a clean, ` +
              `buildable merge. Edit the files directly. Do not leave any <<<<<<< / ` +
              `======= / >>>>>>> markers. Stage your changes with git add.`;

            const resolverEnvelope: NodeEnvelope = {
              correlationId,
              agentId: 'software-teams-programmer',
              status: 'ok',
              input: { prompt: conflictPrompt, context: null },
              result: { text: '' },
              artifacts: [],
            };

            await runAgentTurn(resolverEnvelope, repoContext, githubToken);
          },
        });

        if (mergeResult.kind === 'bounded-failure') {
          const conflictList = mergeResult.conflictingFiles.join(', ');
          const errorText =
            `Finaliser conflict resolution exhausted ${mergeResult.turnsExhausted} ` +
            `resolver turn(s) without producing a clean tree. ` +
            `Conflicting files: ${conflictList}. ` +
            `A human must resolve these conflicts manually.`;

          const errorEnvelope: NodeEnvelope = {
            ...envelope,
            status: 'error',
            result: { text: errorText },
          };

          returnData.push({
            json: toDataObject(errorEnvelope),
            pairedItem: { item: i },
          });
          continue;
        }

        await pushBranch({
          repoDir,
          branchName,
          remote: 'origin',
          githubToken,
        });

        const branchUrl = buildBranchUrl(ownerRepo, branchName);
        const runSummary = buildRunSummary({ agentResults, branchName, ownerRepo, correlationId });

        const successEnvelope: NodeEnvelope = {
          ...envelope,
          agentId: 'software-teams-finaliser',
          status: 'ok',
          result: { text: runSummary },
          artifacts: [
            ...envelope.artifacts,
            { type: 'branch', url: branchUrl },
          ],
        };

        returnData.push({
          json: toDataObject(successEnvelope),
          pairedItem: { item: i },
        });
      } catch (err) {
        if (this.continueOnFail()) {
          returnData.push({
            json: { error: err instanceof Error ? err.message : String(err) },
            pairedItem: { item: i },
          });
          continue;
        }
        throw new NodeOperationError(
          this.getNode(),
          `Software Teams Finaliser failed: ${err instanceof Error ? err.message : String(err)}`,
          { itemIndex: i },
        );
      }
    }

    return [returnData];
  }
}
